<div class="testimonial-area overlay ptb-70 mt-70" style="background: rgba(0, 0, 0, 0) url('<?php echo $this->basePath('/MelisDemoCms/images/bg/testimonial.jpg')?>') no-repeat fixed 50% 50% / cover">
     <div class="container">
         <div class="row">
             <div class="col-xs-12 col-md-8 col-md-push-2">
                 <div class="pagi-03 owl-carousel" style="display: block;">
                     <div class="single-testimonial">
                         <div class="testimonial-img">
                         	<?php echo $this->MelisTag($this->idPage, 'testimonial_image', 'media', '<img src="/MelisDemoCms/images/team/testi-03.jpg" alt="">')?>
                         </div>
                         <div class="testimonial-content color-lightgrey">
                             <div class="name-degi pos-rltv">
                                 <h5><?php echo $this->MelisTag($this->idPage, 'testimonial_title', 'textarea', 'Anik Islam')?></h5>
                                 <p><?php echo $this->MelisTag($this->idPage, 'testimonial_subtitle', 'textarea', 'Developer')?></p>
                             </div>
                             <div class="testi-text">
                                 <p><?php echo $this->MelisTag($this->idPage, 'testimonial_text', 'html', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.')?></p>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
 </div> 