<?php 
    $step1_1  = $this->setup1_1;
    $success  = $step1_1['success'];
    $errors   = $step1_1['errors'];
    $platform = $step1_1['data']['platform'];
    $module   = $step1_1['data']['module'];
    
    $markupSuccess = '<li><i class="fa fa-check fa-color-green"></i> <span>%s</span></li>';
    $markupError   = '<li><i class="fa fa-times fa-color-red"></i> <span>%s</span></li>';
    $disabled = $success === 1 ? 'setup-pass-page  btn btn-success' : 'btn btn-default';
?>
<!-- STEP 1.1 -->
<div class="item">
	<div class="setup-content-container">
		<div class="setup-heading">
			<h2><?= $this->translate('tr_melis_installer_layout_vhost'); ?></h2> 
			<p><?= $this->translate('tr_melis_installer_layout_vhost_subtext'); ?></p>	
		</div>
    	
    	<div class="setup-content setup-p1-1">
    		<ul class="list-unstyled setup-check-list">
				<?php 
    				if(!empty($platform)) {
    				    echo sprintf($markupSuccess, $this->translate('tr_melis_installer_step_1_1_platform').': '.$platform);
    				} else {
    				    echo sprintf($markupError, $errors['platform']);
    				}
    				
    				if(!empty($module)) {
    				    echo sprintf($markupSuccess, $this->translate('tr_melis_installer_step_1_1_module').': '.$module);
    				} else {
    				    echo sprintf($markupError, $errors['module']);
    				}
				?>
  			</ul>
  			<?php if (!empty($errors)){?>
      			<div class="alert alert-info">
      				<?= $this->translate('tr_melis_installer_step_1_1_example_vhost_config')?>
      			</div>
  			<?php }?>
	    	<div class="setup-button-cont">
     			<a class="<?= $disabled; ?>"><?= $this->translate('tr_melis_installer_common_next'); ?></a>
     		</div>
    	</div>
	</div>
</div>