
<!-- STEP 1.3 -->
<div class="item">
	<div class="setup-content-container">
		<div class="setup-heading">
			<h2><?= $this->translate('tr_melis_installer_layout_env'); ?></h2> 
			<p><?= $this->translate('tr_melis_installer_layout_env_subtext'); ?></p>	
		</div>
    	<div class="setup-content setup-p1-3">
    		<div class="row">
    			<form id="environment-form" method="post" >
	    			<div class="col-xs-12 col-md-6">
	    				<div class="environment-cont default-environment">
							<h4 class="no-padding-top border-bottom"><?= $this->translate('tr_melis_installer_layout_env_default_env'); ?></h4>
							
							<div class="form-group">
								<label><?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?></label>
								<input type="text" class="form-control"  placeholder="<?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?>"  name="environment_name" value="<?= $this->setup1_3_env_name; ?>" disabled>
							</div>
							
							<div class="form-group hidden">
								<label><?= $this->translate('tr_melis_installer_layout_env_back_office_domain'); ?></label>
								<input type="url" class="form-control"  placeholder="<?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?>" name="domain" value="<?= $this->setup1_3_env_domain; ?>" required>
							</div>
							
							<div class="form-group">
                                <label><?= $this->translate('tr_melis_installer_layout_env_advance_parameters'); ?> <i class="fa fa-plus pull-right melis-install-adv-prop-trigger" aria-hidden="true" title="Tooltip on left"></i></label>
                            </div>
                            <div class="melis-install-adv-prop-content">
                                <div class="form-group">
                                    <?php
                                        $emailEnabled = null;
                                        $sendEmailVal = isset($this->setup1_3_current['app_interface_conf']['send_email']) ? $this->setup1_3_current['app_interface_conf']['send_email'] : false;
                                        if((bool) $sendEmailVal) {
                                            $emailEnabled = 'checked';
                                        }
                                    ?>
                                    <label><?= $this->translate('tr_melis_installer_layout_env_send_email'); ?><i class="fa fa-info-circle pull-right" data-toggle="tooltip" aria-hidden="true" title="<?= $this->translate('tr_melis_installer_layout_env_send_email_info')?>"></i></label>
                                    <div  class="make-switch module-switch" data-on-label="<?= $this->translate('tr_melis_installer_layout_env_send_email_enabled'); ?>" data-off-label="<?= $this->translate('tr_melis_installer_layout_env_send_email_disabled'); ?>" data-text-label="<?= $this->translate('tr_melis_installer_common_status'); ?>">
                                        <input name="send_email" type="checkbox" <?= $emailEnabled ?>/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label><?= $this->translate('tr_melis_installer_layout_env_error_reporting'); ?><i class="fa fa-info-circle pull-right" data-toggle="tooltip" aria-hidden="true" title="<?= $this->translate('tr_melis_installer_layout_env_error_reporting_info')?>"></i></label>
                                    <select name="error_reporting" class="form-control">
                                        <option value="E_ALL & ~E_USER_DEPRECATED" <?= (!empty($this->setup1_3_current) && $this->setup1_3_current['app_interface_conf']['error_reporting'] == 'E_ALL & ~E_USER_DEPRECATED') ? 'selected' : ''?>><?= $this->translate('tr_melis_installer_layout_env_error_reporting_all'); ?></option>
                                        <option value="0" <?= (!empty($this->setup1_3_current) && $this->setup1_3_current['app_interface_conf']['error_reporting'] == '0') ? 'selected' : ''?>><?= $this->translate('tr_melis_installer_layout_env_error_reporting_off'); ?></option>
                                    </select>
                                </div>
                            </div>
						</div>
						<div class="setup-button-cont">
			     			<a class="btn btn-success setup-pass-page"><?= $this->translate('tr_melis_installer_common_next'); ?></a>
			     		</div>
	    			</div>
	    			<div class="col-xs-12 col-md-6">
						<div class="add-environment text-right">
							<a href="#" class="btn btn-success">
								<i class="fa fa-plus"></i>
								<span><?= $this->translate('tr_melis_installer_layout_env_add_env'); ?></span>
							</a>
						</div>
						<div class="add-environment-container">
							<!-- additional environment will appear here -->
							<?php 
    							$ctr = 1;
    							if(!empty($this->setup1_3)){
        							foreach($this->setup1_3 as $env => $envValues) { 
        							    foreach($envValues as $values) {
							?>
        							<div class="environment-cont entry">
                                        <div class="form-group">
                                            <label><?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?><a class="btn btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i> <?= $this->translate('tr_melis_installer_layout_env_remove'); ?></a></label>
                                            <input type="text" class="form-control" placeholder="<?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?>" name="environment_name_<?= $ctr; ?>" value="<?= $values['sdom_env']; ?>" required>
                                        </div>
                                        <div class="form-group">
                                            <label><?= $this->translate('tr_melis_installer_layout_env_back_office_domain'); ?></label>
                                            <input type="url" class="form-control" placeholder="<?= $this->translate('tr_melis_installer_layout_env_back_office_domain'); ?>" name="domain_<?= $ctr; ?>" value="<?= $values['sdom_domain']; ?>" required>
                                        </div>
        								<div class="form-group">
                                            <label><?= $this->translate('tr_melis_installer_layout_env_advance_parameters'); ?> <i class="fa fa-plus pull-right melis-install-adv-prop-trigger" aria-hidden="true" title="Tooltip on left"></i></label>
                                        </div>
                                    	<div class="melis-install-adv-prop-content">
                                            <div class="form-group">
                                                <?php
                                                    $emailEnabled = null;
                                                    $sendEmail = isset($values['app_interface_conf']['send_email']) ? $values['app_interface_conf']['send_email'] : false;
                                                    if((bool) $sendEmail) {
                                                        $emailEnabled = 'checked';
                                                    }
                                                ?>
                                                <label><?= $this->translate('tr_melis_installer_layout_env_send_email'); ?></label>
                                                <div  class="make-switch module-switch" data-on-label="<?= $this->translate('tr_melis_installer_layout_env_send_email_enabled'); ?>" data-off-label="<?= $this->translate('tr_melis_installer_layout_env_send_email_disabled'); ?>" data-text-label="<?= $this->translate('tr_melis_installer_common_status'); ?>">
                                                    <input name="send_email_<?= $ctr; ?>" type="checkbox" <?= $emailEnabled; ?>/>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label><?= $this->translate('tr_melis_installer_layout_env_error_reporting'); ?></label>
                                                <select name="error_reporting_<?= $ctr; ?>" class="form-control">
                                                    <option value="E_ALL & ~E_USER_DEPRECATED" <?= ($values['app_interface_conf']['error_reporting'] == 'E_ALL & ~E_USER_DEPRECATED') ? 'selected' : ''?>><?= $this->translate('tr_melis_installer_layout_env_error_reporting_all'); ?></option>
                                                    <option value="0" <?= ($values['app_interface_conf']['error_reporting'] == '0') ? 'selected' : ''?>><?= $this->translate('tr_melis_installer_layout_env_error_reporting_off'); ?></option>
                                                </select>
                                            </div>
                                        </div>
                                    </div> 
							<?php 
        							    }
        							    $ctr++;
        							}
    							} 
							?>
						</div>
	    			</div>
    			</form>
    		</div>
    	</div>
	</div>
</div>