<!-- STEP 1.3 -->
<div class="item">
	<div class="setup-content-container">
	
		<div class="setup-heading">
			<h2><?= $this->translate('tr_melis_installer_layout_env'); ?></h2> 
			<p><?= $this->translate('tr_melis_installer_layout_env_subtext'); ?></p>	
		</div>
    	
    	<div class="setup-content setup-p1-3">
    	
    		<div class="row">
    			<form id="environment-form" method="post" >
	    			<div class="col-xs-12 col-md-6">
	    				<div class="environment-cont default-environment">
							<h4 class="no-padding-top border-bottom"><?= $this->translate('tr_melis_installer_layout_env_default_env'); ?></h4>
							
							<div class="form-group">
								<label><?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?></label>
								<input type="text" class="form-control"  placeholder="<?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?>"  name="environment_name" value="<?= $this->setup1_3_env_name; ?>" disabled>
							</div>
							
							<div class="form-group">
								<label><?= $this->translate('tr_melis_installer_layout_env_back_office_domain'); ?></label>
								<input type="url" class="form-control"  placeholder="<?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?>" name="domain" value="<?= $this->setup1_3_env_domain; ?>" required>
							</div>
						</div>
						
						<div class="setup-button-cont">
			     			<a class="btn btn-success setup-pass-page"><?= $this->translate('tr_melis_installer_common_next'); ?></a>
			     		</div>

	    			</div>
	    			
	    			<div class="col-xs-12 col-md-6">
	    			
						<div class="add-environment text-right">
							<a href="#" class="btn btn-success">
								<i class="fa fa-plus"></i>
								<span><?= $this->translate('tr_melis_installer_layout_env_add_env'); ?></span>
							</a>
						</div>
						
						<div class="add-environment-container">
							<!-- additional environment will appear here -->
							<?php 
							$ctr = 1;

							if(!empty($this->setup1_3)):

							foreach($this->setup1_3 as $env => $envValues) { 
							    foreach($envValues as $values) {

							?>
							<div class="environment-cont entry">
                                <div class="form-group">
                                    <label><?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?></label><a class="btn btn-danger"><?= $this->translate('tr_melis_installer_layout_env_remove'); ?></a>
                                    <input type="text" class="form-control" placeholder="<?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?>" name="environment_name_<?= $ctr; ?>" value="<?= $values['sdom_env']; ?>" required>
                                </div>
                                <div class="form-group">
                                    <label><?= $this->translate('tr_melis_installer_layout_env_back_office_domain'); ?></label>
                                    <input type="url" class="form-control" placeholder="<?= $this->translate('tr_melis_installer_layout_env_back_office_domain'); ?>" name="domain_<?= $ctr; ?>" value="<?= $values['sdom_domain']; ?>" required>
                                </div>
                            </div> 
							<?php 
							    }
							     $ctr++;
							}
							
							endif; ?>
							
						</div>
						

	    			</div>
    			</form>
    		</div>

    	</div>
		
	</div>
</div>