<?php if(!empty($this->showSlider)){?>
	<div class="owl-carousel w-bg aboutus-slider-owl" id="<?= $this->pluginId; ?>">
		<?php foreach ($this->showSlider As $key => $val){?>
			<!-- single team start-->
            <div class="single-product single-member">
                <div class="product-img">
                    <div class="single-prodcut-img product-overlay pos-rltv">
                        <img alt="" src="<?php echo $val->mcsdetail_img?>">
                    </div>
                    <div class="product-icon socile-icon-tooltip text-center">
                        <ul>
                            <li><a data-tooltip="Facebook" href="https://www.facebook.com/melistechnology" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
                            <li><a data-tooltip="Twitter" href="https://twitter.com/meliscms" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
                            <li><a data-tooltip="LinkedIn" href="https://www.linkedin.com/company/melis-technology" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li>
                        </ul>
                    </div>
                    <div class="member-info">
                        <h5><?php echo $val->mcsdetail_title?></h5>
                        <p><?php echo $val->mcsdetail_sub1?></p>
                    </div>
                </div>
            </div>
            <!-- single team end-->
		<?php }?>
	</div>
<?php }else{?>
	<div class="alert alert-warning" role="alert">
    	No result
    </div>
<?php }?>
