<?php 
    /**
     * From layout variable $newsDetailsPageId is accessible
     * $newsDetailsPageId is the Page Id where the News details display
     */
    $newsDetailsPageId = $this->layout()->siteDatas['news_details_page_id'];
?>
<div class="total-blog-owl owl-carousel w-bg">
	<?php foreach ($this->latestNews As $key => $val):?>
    	<?php $newsLink = $this->MelisLink($newsDetailsPageId, true).'?newsid='.$val->cnews_id ?>
       	<div class="single-blog">
           	<div class="blog-img pos-rltv product-overlay">
           		<?php if (!empty($val->cnews_image1)):?>
               		<a href="<?php echo $newsLink ?>"><img src="<?php echo $val->cnews_image1?>" alt=""></a>
               	<?php endif;?>
           	</div>
           	<div class="blog-content">
               	<div class="blog-title">
                   	<h5 class="uppercase font-bold"><a href="<?php echo $newsLink ?>"><?php echo $val->cnews_title?></a></h5>
                   	<div class="like-comments-date">
                       	<ul>
                       		<li></li>
                           	<li class="blog-date text-danger"><i class="zmdi zmdi-calendar-alt"></i> <?php echo date('d M Y',strtotime(($val->cnews_publish_date) ? $val->cnews_publish_date : $val->cnews_creation_date))?></li>
                       	</ul>
                   	</div>
                   	<div class="blog-text">
                       	<p><?php echo $val->cnews_paragraph1 ?></p>
                   	</div>
                   	<a class="read-more montserrat" href="<?php echo $newsLink ?>">Read More</a>
               	</div>
           	</div>
       	</div> 
   	<?php endforeach;?>
</div>