<?php if(!empty($this->menu)){?>
    <!-- <div class="col-md-8 col-sm-10 hidden-xs"> -->
    <nav id="primary-menu" class="hidden-xs">
        <ul class="main-menu">
            <?php
        	    foreach ($this->menu As $key => $val)
        	    {
        	        if (in_array($val['pageType'], array('PAGE', 'SITE')))
        	        {
            	        $pageName = $val['label'];
            	        $hasChild = (!empty($val['pages']) && count($val['pages']) > 0) ? 'class="mega-parent"' : '';
            	        echo '<li '.$hasChild.'>';
            	        echo '<a href="'.$val['uri'].'">'.$pageName.'</a>';
            	        
            	        if (!empty($val['pages']) && count($val['pages']) > 0)
            	        {
            	            $newsClass = '';
            	            if ($val['idPage'] == $this->layout()->siteDatas['news_menu_page_id'])
            	            {
            	                $newsClass = 'news-menu-area';
            	            }
            	            
            	            echo '<div class="mega-menu-area '.$newsClass.' mma-970">';
            	            foreach ($val['pages'] As $sHkey => $sHVal)
            	            {
                	            echo '<ul class="single-mega-item coloum-4">';
                	                
                	            $subTitlePageName = $sHVal['label'];
        	                    
                	            echo '<li class="menu-title uppercase"><a href="'.$sHVal['uri'].'" >'.$subTitlePageName.'</a></li>';
        	                    
        	                    if (!empty($sHVal['pages']))
        	                    {
        	                        foreach ($sHVal['pages'] As $sHLkey => $sHLVal)
        	                        {
        	                            $subPageName = $sHLVal['label'];
        	                            
        	                            echo '<li><a href="'.$sHLVal['uri'].'">'.$subPageName.'</a></li>';
        	                        }
        	                    }
            	                    
            	                if (count($val['pages']) == ($sHkey + 1))
            	                {
            	                    echo '<li>&nbsp;</li><li class="menu-title-all"><a href="'.$val['uri'].'">SEE ALL '.strtoupper($pageName).'</a></li>';
            	                }
        	                    echo '</ul>';
    	                    }
    	                    
        	                echo '</div>';
            	        }
        	            echo '</li>';
        	        }
            	}
            ?>
        </ul>
    </nav>
    <!-- </div> -->
    
    <!-- mobile-menu-area start -->
    <div class="mobile-menu-area">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <nav id="dropdown">
                        <ul>
                        	<li>
                            	<form action="<?php echo $this->MelisLink($this->layout()->siteDatas['search_result_page_id'], false)?>" method="get">
                                    <div class="input-box">
                                        <input class="mobile-search-input" placeholder="Search" type="text" name="search" value="<?php echo $this->layout()->search?>" required>
                                        <button class="src-btn mobile-search-btn"><i class="fa fa-search fa-2x"></i></button>
                                    </div>
                                </form>
                            </li>
                            <?php
                        	    foreach ($this->menu As $key => $val)
                        	    {
                        	        if (in_array($val['pageType'], array('PAGE', 'SITE')))
                        	        {
                            	        $pageName = $val['label'];
                            	        echo '<li>';
                            	        echo '<a href="'.$val['uri'].'">'.$pageName.'</a>';
                            	        
                            	        if (!empty($val['pages']))
                            	        {
                            	            echo '<ul class="single-mega-item">';
                                	            foreach ($val['pages'] As $sHkey => $sHVal)
                                	            {
                                    	            $subTitlePageName = $sHVal['label'];
                            	                    
                                    	            echo '<li><a href="'.$val['uri'].'" >'.$subTitlePageName.'</a>';
                            	                    
                            	                    if (!empty($sHVal['pages']))
                            	                    {
                            	                        echo '<ul class="single-mega-item">';
                            	                        
                            	                        foreach ($sHVal['pages'] As $sHLkey => $sHLVal)
                            	                        {
                            	                            $subPageName = $sHLVal['label'];
                            	                            
                            	                            echo '<li><a href="'.$val['uri'].'">'.$subPageName.'</a></li>';
                            	                        }
                            	                        echo '</ul>';
                            	                    }
                            	                    
                            	                    if (count($val['pages']) == ($sHkey + 1))
                            	                    {
                            	                        echo '<li class="menu-title-all"><a href="'.$val['uri'].'">SEE ALL '.strtoupper($pageName).'</a></li>';
                            	                    }
                                	                
                            	                    echo '</li>';
                        	                    }
                        	                    
                    	                    echo '</ul>';
                    	                    
                            	        }
                        	            echo '</li>';
                        	        }
                        	    }
                            ?>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
<!--mobile menu area end-->
<?php }else{?>
	<div class="alert alert-warning" role="alert">
    	No result
    </div>
<?php }?>