<?php 
    /**
     * From layout variable $newsDetailsPageId is accessible
     * $newsDetailsPageId is the Page Id where the News details display
     */
    $newsDetailsPageId = $this->layout()->siteDatas['news_details_page_id'];
?>
<?php if ($this->listNews->count()):?>
    <div class="row">
       <div class="total-blog">
       		<?php foreach ($this->listNews As $key => $val):?>
       			<?php $newsLink = $this->MelisLink($newsDetailsPageId, true).'?newsid='.$val->cnews_id ?>
                <div class="col-md-4">
                   	<div class="single-blog">
                   		<?php if (!empty($val->cnews_image1)):?>
                           	<div class="blog-img pos-rltv product-overlay">
                               	<a href="<?php echo $newsLink ?>"><img src="<?php echo $val->cnews_image1?>"></a>
                           	</div>
                       	<?php endif;?>
                       	<div class="blog-content">
                           	<div class="blog-title">
                               	<h5 class="uppercase font-bold">
                           			<a href="<?php echo $newsLink ?>"><?php echo $val->cnews_title?></a>
                           		</h5>
                               	<div class="like-comments-date">
                                   	<ul>
                                       	<li></li>
                                       	<li class="blog-date text-danger">
                                       		<i class="zmdi zmdi-calendar-alt"></i> <?php echo date('d M Y',strtotime(($val->cnews_publish_date) ? $val->cnews_publish_date : $val->cnews_creation_date))?>
                                   		</li>
                                   	</ul>
                               	</div>
                               	<div class="blog-text">
                                   	<p><?php echo $val->cnews_paragraph1?></p>
                               	</div>
                               	<a class="read-more montserrat" href="<?php echo $newsLink ?>">Read More</a>
                           	</div>
                       	</div>
                   	</div> 
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php else:?>    
	<h4 class="search-results-title">No Result</h4>
<?php endif;?>

<!-- Pagination -->
<?php 
    // Generating Pagination Control using partial view
    echo $this->paginationControl($this->listNews, 'Sliding', 'MelisDemoCms/plugin/list-paginator', 
                                array('nbPageBeforeAfter' => $this->nbPageBeforeAfter)); 
?>