<?php if (!empty($this->listofpages)):?>
    <div class="total-testimonial-owl pagi-03 owl-carousel" id="testimonial-<?= $this->pluginId; ?>">
    	<?php 
    	    // Testimonials handler
    	    $testimonials = array();
    	    foreach ($this->listofpages As $key => $val)
	        {
	            $pageData = array();
	            
	            /**
	             * List of tags use to create MelisTags in Testimonials on Back-Office
	             */
	            $testimonialTags = array('testimonial_image', 'testimonial_title', 'testimonial_subtitle', 'testimonial_text');
	            
	            $pageContent = $val->page_tags;
	            foreach ($pageContent As $cKey => $cVal)
	            {
	                /**
                     * Checking if the $cKey is exist on Testimonials tags
                     */
	                if (in_array($cKey, $testimonialTags))
	                {
	                    $pageData[$cKey] = $cVal;
	                }
	            }
	            
	            if (!empty($pageData))
	            {
	                // Pusing to the Testimonials handler after gathering each testimonial details
	                array_push($testimonials, $pageData);
	            }
    	    }
		?>
		<?php if (!empty($testimonials)):?>
			<?php foreach ($testimonials As $key => $val):?>
                <div class="single-testimonial">
                	<?php if (!empty($val['testimonial_image'])): ?>
                        <div class="testimonial-img">
                            <?php echo $val['testimonial_image'] ?>
                        </div>
                    <?php endif;?>
                    <div class="testimonial-content color-lightgrey">
                        <div class="name-degi pos-rltv">
                            <h5><?php echo (!empty($val['testimonial_title'])) ? $val['testimonial_title'] : '' ?></h5>
                            <p><?php echo (!empty($val['testimonial_subtitle'])) ? $val['testimonial_subtitle'] : '' ?></p>
                        </div>
                        <div class="testi-text">
                            <p><?php echo (!empty($val['testimonial_text'])) ? $val['testimonial_text'] : '' ?></p>
                        </div>
                    </div>
                </div>
            <?php endforeach;?>
        <?php else: ?>
            <div class="alert alert-warning">
                No data found
            </div>
        <?php endif;?>
    </div>
 <?php else: ?>
    <div class="alert alert-warning">
        No Result
    </div>
<?php endif;?>