<div class="home-page">
    <!-- Homepage Header Slider -->
    <?php echo $this->homePageSlider ?>
    <!-- End of Homepage Header Slider -->
    
    <div class="full-width row">
    	<div class="col-xs-12">
    		<?php echo $this->MelisDragDropZone($this->idPage, "dragdropzone_home_1") ?>
    	</div>
    	<div class="col-xs-12">
        	<!--Delivery Service Start-->
            <?php 
                echo $this->MelisTag($this->idPage, "homepage_line_1", 'html', 
                '<div class="delivery-service-area ptb-30">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="single-service shadow-box text-center">
                                    <img src="'.$this->basePath('/MelisDemoCms/images/icons/trending.png').'" alt="">
                                    <h5>Money Back Guarantee</h5>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="single-service shadow-box text-center">
                                    <img src="'.$this->basePath('/MelisDemoCms/images/icons/news.png').'" alt="">
                                    <h5>Gift Coupon</h5>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="single-service shadow-box text-center">
                                    <img src="'.$this->basePath('/MelisDemoCms/images/icons/live.png').'" alt="">
                                    <h5>Free Shipping</h5>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="single-service shadow-box text-center">
                                    <img src="'.$this->basePath('/MelisDemoCms/images/icons/chat.png').'" alt="">
                                    <h5>24x7 Support</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>');
            ?>
            <!-- End of Delivery Service-->
    	</div>
    </div>
    
    <div class="full-width row">
    	<div class="col-xs-12">
    		<!-- Paragraphs -->
            <?php 
                echo $this->MelisTag($this->idPage, "homepage_line_2", 'html',
                '<div class="blog-area pb-70">
                    <div class="container">
                        <div class="row">
                	        <div class="col-md-12 col-sm-8 col-xs-12">
                	           <div class="single-blog-body">
                	               <div class="single-blog sb-2 mb-30">
                				        <div class="blog-content">
                			                <div class="blog-title">
                			                    <h5 class="uppercase font-bold">New fashion collection 2016</h5>
                			                    <div class="blog-text">
                			                        <p>There are many variations of passages of Lorem Ipsum available, but the majority suffered alteration in some form, by injected humour, 
                                                        or random ised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, 
                                                        you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum. 
                                                        <br><br>generators on the Internet tend to repeat predefined chunks as necessary. 
                                                        There are many variations of passages of Lorem Ipsum available the Internet tend to repeat 
                                                        predefined chunks as necessary. There are many variations of passages of Lorem Ipsum available
                                                    </p>
                			                    </div>
                			                </div>
                			                <div class="blockqot mtb-30">
                			                    <blockquote><p>There are many variations of passages of Lorem Ipsum available, but majority have suffered alteration in some form, by injected humour. There are many variations of passages of Lorem Ipsum available, but the majorit. There are many variations of passages of Lorem Ipsum available, but the majorit.</p></blockquote>
                			                </div>
                	                    </div>
                	                </div>
                	            </div>
                	        </div>
                    	</div>
                	</div>
                </div>');
            ?>
            <!-- End of Paragraphs -->
    	</div>
    </div>
    
    <!-- Big Right Image -->
    <div class="blog-area pb-70">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-md-push-8 col-sm-4 col-xs-12">
                	<?php echo $this->MelisTag($this->idPage, "homepage_line_3_img", 'media',
                	    '<img class="img-responsive" src="/MelisDemoCms/images/news/N01.jpg" alt="">')?>
                </div>
                <div class="col-md-7 col-md-pull-4 col-sm-8 col-xs-12">
                   <div class="single-blog-body">
                       <div class="single-blog sb-2 mb-30">
                            <div class="blog-content">
                                <div class="blog-title">
                                	<?php echo $this->MelisTag($this->idPage, "homepage_line_3", 'html',
                                        '<h5 class="uppercase font-bold">New fashion collection 2016</h5>
                                        <div class="blog-text">
                                            <p>There are many variations of passages of Lorem Ipsum available, but the majority suffered alteration in some form, by injected humour, or random ised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum. <br><br>generators on the Internet tend to repeat predefined chunks as necessary. There are many variations of passages of Lorem Ipsum available the Internet tend to repeat predefined chunks as necessary. There are many variations of passages of Lorem Ipsum available</p>
                                        </div>
                            	    ')?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Big Left Image -->
    <div class="blog-area pb-70">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <?php echo $this->MelisTag($this->idPage, "homepage_line_4_img", 'media',
                	    '<img class="img-responsive" src="/MelisDemoCms/images/product/shoes/03/03.jpg" alt="">')?>
                </div>
                <div class="col-md-7 col-md-push-1 col-sm-8 col-xs-12">
                   <div class="single-blog-body">
                       <div class="single-blog sb-2 mb-30">
                            <div class="blog-content">
                                <div class="blog-title">
                                    <?php echo $this->MelisTag($this->idPage, "homepage_line_4", 'html',
                                        '<h5 class="uppercase font-bold">New fashion collection 2016</h5>
                                        <div class="blog-text">
                                            <p>There are many variations of passages of Lorem Ipsum available, but the majority suffered alteration in some form, by injected humour, or random ised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum. <br><br>generators on the Internet tend to repeat predefined chunks as necessary. There are many variations of passages of Lorem Ipsum available the Internet tend to repeat predefined chunks as necessary. There are many variations of passages of Lorem Ipsum available</p>
                                        </div>
                            	    ')?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
     
    <!--blog area are start-->
    <div class="blog-area pb-70">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-center">
                   <div class="heading-title heading-style pos-rltv mb-50 text-center">
                       <h5 class="uppercase"><?php echo $this->MelisTag($this->idPage, "homepage_news_title", 'textarea','News')?></h5>
                   </div>
               </div>
           </div>
           
    		<!-- Latest News -->
           	<?php echo $this->latestNews?>
            <!-- End of Latest News -->
            
        </div>
    </div>
    <!--blog area are end-->
    
    <!--testimonial-area-start-->
    <div class="testimonial-area overlay ptb-70 mt-70" style="background: rgba(0, 0, 0, 0) url('<?php echo $this->basePath('/MelisDemoCms/images/bg/testimonial.jpg')?>') no-repeat fixed 50% 50% / cover">
         <div class="container">
             <div class="row">
                <div class="col-xs-12 text-center">
                    <div class="heading-title color-lightgrey mb-40 text-center">
                        <h5 class="uppercase"><?php echo $this->MelisTag($this->idPage, 'homepage_testimonial_title', 'textarea', 'Testimonial')?></h5> 
                    </div>
                </div>
                 <div class="col-xs-12 col-md-8 col-md-push-2">
                    <?php echo $this->testimonialList ?>
                 </div>
             </div>
         </div>
     </div>        
    <!--testimonial-area-end-->
    
    <!--brand area are start-->
    <div class="brand-area ptb-60">
        <div class="container">
               <div class="total-brand-owl owl-carousel w-bg">
                    <div class="single-brand shadow-box"><a href="#"><img src="<?php echo $this->basePath('/MelisDemoCms/images/brand/01.png')?>" alt=""></a></div>
                    <div class="single-brand shadow-box"><a href="#"><img src="<?php echo $this->basePath('/MelisDemoCms/images/brand/02.png')?>" alt=""></a></div>
                    <div class="single-brand shadow-box"><a href="#"><img src="<?php echo $this->basePath('/MelisDemoCms/images/brand/03.png')?>" alt=""></a></div>
                    <div class="single-brand shadow-box"><a href="#"><img src="<?php echo $this->basePath('/MelisDemoCms/images/brand/04.png')?>" alt=""></a></div>
                    <div class="single-brand shadow-box"><a href="#"><img src="<?php echo $this->basePath('/MelisDemoCms/images/brand/05.png')?>" alt=""></a></div>
                    <div class="single-brand shadow-box"><a href="#"><img src="<?php echo $this->basePath('/MelisDemoCms/images/brand/06.png')?>" alt=""></a></div>
                    <div class="single-brand shadow-box"><a href="#"><img src="<?php echo $this->basePath('/MelisDemoCms/images/brand/01.png')?>" alt=""></a></div>
                    <div class="single-brand shadow-box"><a href="#"><img src="<?php echo $this->basePath('/MelisDemoCms/images/brand/02.png')?>" alt=""></a></div>
                    <div class="single-brand shadow-box"><a href="#"><img src="<?php echo $this->basePath('/MelisDemoCms/images/brand/03.png')?>" alt=""></a></div>
                    <div class="single-brand shadow-box"><a href="#"><img src="<?php echo $this->basePath('/MelisDemoCms/images/brand/04.png')?>" alt=""></a></div>
            </div>
      </div>
    </div>
    <!--brand area are start--> 
</div>