<!-- STEP 3.2 -->
<div class="item">
    <div class="setup-content-container">
        <div class="setup-heading">
            <h2><?= $this->translate('tr_melis_installer_navigation_modules') . ' / ' . $this->translate('melis_installer_common_configuration'); ?></h2>
            <p><?= $this->translate('melis_installer_configuration_subtitle'); ?></p>
        </div>
        <div class="setup-content setup-p3">
            <div class="row" id="melis-installer-configuration-forms">

            </div>
            <div class="setup-button-cont">
                <a class="btn btn-success setup-pass-page"><?= $this->translate('tr_melis_installer_common_next'); ?></a>
            </div>
        </div>
    </div>
</div>