<!-- STEP 3.2 -->
<div class="item">
    <div class="setup-content-container">
        <div class="setup-heading">
            <h2>Step 3.2: <?= $this->translate('melis_installer_download_module_title') ?></h2>
            <p><?= $this->translate('melis_installer_download_module_subtitle') ?></p>

        </div>

        <div class="setup-content setup-p3 mt-25">
            <div class="row">
                <div class="col-xs-12 col-md-12">
                    <pre id="melis-installer-event-do-response"><i class="fa fa-spinner fa-spin"></i> <?= $this->translate('melis_installer_common_downloading')?></pre>

                    <div class="setup-button-cont">
                        <a class="btn btn-success setup-pass-page disabled" disabled><?= $this->translate('tr_melis_installer_common_next'); ?></a>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
