<!-- STEP 3.1 -->
<div class="item">
    <div class="setup-content-container">
        <div class="setup-heading">
            <h2>Step 3.1: Modules / Selection</h2>
            <p>Selection of the additional modules to install and enable</p>

        </div>

        <div class="setup-content setup-p3 mt-25">
            <div class="row">
                <div class="col-xs-12 col-md-12">
                    <h2>Modules to install</h2>
                    <form role="form" id="frmSelModules" class="form-group form-modules">
                        <div class="row">
                            <?php foreach($this->packagistMelisModules as $module):?>
                                <?php if(in_array($module['packageModuleName'], $this->setup3_3_selected) || in_array($module['packageModuleName'], $this->setup3_3_requiredModules)) :?>
                                    <?php $requredModule = (in_array($module['packageModuleName'], $this->setup3_3_requiredModules)) ? 'requried-module' : ''?>
                                    <div class="col-md-6">
                                        <div class="checkbox">
                                            <div class="checkbox cb-cont" style="position:relative">
                                                <label>
                                                <span class="cbmask-outer clearfix">
                                                    <span  class="cbmask-inner cb-modules-mask"></span>
                                                </span>
                                                    <input type="checkbox" class="<?= $requredModule?>" name="chk<?= $module['packageModuleName']; ?>" value="<?= $module['packageModuleName']; ?>" data-package="<?= $module['packageName'] ?>" checked>
                                                </label>
                                                <span class="module-name"><?= $module['packageTitle']; ?></span>
                                                <i class="fa fa-info-circle pull-right" aria-hidden="true" data-toggle="tooltip" title="<?= $module['packageSubtitle'] ?>"></i>
                                            </div>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <div class="col-md-6">
                                        <div class="checkbox">
                                            <div class="checkbox cb-cont" style="position:relative">
                                                <label class="remember-me-cont">
                                                <span class="cbmask-outer clearfix">
                                                    <span  class="cbmask-inner cb-modules-mask"></span>
                                                </span>
                                                    <input type="checkbox" value="<?= $module['packageModuleName']; ?>" name="chk<?= $module['packageModuleName']; ?>" data-package="<?= $module['packageName'] ?>">
                                                </label>
                                                <span class="module-name"><?= $module['packageTitle']; ?></span>
                                                <i class="fa fa-info-circle pull-right" aria-hidden="true" data-toggle="tooltip" title="<?= $module['packageSubtitle'] ?>"></i>

                                            </div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    </form>

                    <form role="form" id="frmSelector">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="checkbox">
                                    <div class="checkbox cb-cont" style="position:relative">
                                        <label class="remember-me-cont">
                                            <span class="cbmask-outer clearfix">
                                                <?php $allSelected = (count($this->packagistMelisModules) == count($this->setup3_3_selected)) ? 'cb-active' : '';?>
                                                <span class="cbmask-inner <?= $allSelected?>"></span>
                                            </span>
                                            <input type="checkbox" id="chkSelectAllModules">
                                        </label>
                                        <span class="module-name"><?= $this->translate('tr_melis_installer_melis_modules_select_all'); ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <br/> <br/>
                </div>
            </div>
        </div>

        <div class="setup-heading">
            <h2>Site to install (optional)</h2>
            <p>You can choose a site to install along with MelisCms setup</p>
        </div>
        <div class="setup-content setup-p3 mt-25" id="setup-step3">

                <div class="row">
                    <div class="col-xs-12">
                        <?php
                        $form = $this->setup3_webConfigOption;
                        echo $this->form()->openTag($form);
                        $webOption = $form->get('weboption')->getValue();
                        ?>
                        <ul class="list-group">
                            <li class="list-group-item">
                                <div class="font-awesome-radio-container pull-left">
                                    <input id="weboption-none" type="radio" class="font-awesome-radio weboption-radio" name="weboption" value="None" <?= ($webOption == 'None') ? 'checked' : ''?>>
                                    <label for="weboption-none"></label>
                                </div>
                                <?= $this->translate('tr_melis_installer_option_none'); ?>
                            </li>
                            <li class="list-group-item">
                                <div class="font-awesome-radio-container pull-left">
                                    <input id="weboption-newsite" type="radio" class="font-awesome-radio weboption-radio" name="weboption" value="NewSite" <?= ($webOption == 'NewSite')? 'checked' : ''?>>
                                    <label for="weboption-newsite"></label>
                                </div>
                                <?= $this->translate('tr_melis_installer_option_new_website'); ?>
                            </li>
                            <li class="list-group-item">
                                <div class="font-awesome-radio-container pull-left">
                                    <input id="weboption-democms" type="radio" class="font-awesome-radio weboption-radio" name="weboption" value="MelisDemoCms" <?= ($webOption == 'MelisDemoCms' || empty($webOption)) ? 'checked' : ''?>>
                                    <label for="weboption-democms"></label>
                                </div>
                                <?= $this->translate('tr_melis_installer_option_use_demo_cms'); ?>
                            </li>
                        </ul>
                        <?php
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <div class="setup3-webform <?php echo (!$this->setup3_showWebForm) ? 'hidden' : '' ?>">
                            <h4 class="border-bottom"><?php echo $this->translate('tr_melis_installer_web_config_create_web_sel_language')?></h4>
                            <?php
                            $form = $this->setup3_webLangForm;
                            echo $this->form()->openTag($form);
                            echo $this->melisFieldCollection($form);
                            echo $this->form()->closeTag();

                            $form = $this->setup3_webForm;
                            $siteName = $form->get('website_name');
                            $siteModule = $form->get('website_module');
                            if(!$siteName->getValue()) {
                                $siteName->setValue(getenv('MELIS_MODULE'));
                            }
                            if(!$siteModule->getValue()) {
                                $siteModule->setValue(getenv('MELIS_MODULE'));
                            }
                            echo $this->form()->openTag($form);
                            echo $this->melisFieldCollection($form);
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                    </div>
                </div>

            <div class="setup-button-cont">
                <a class="btn btn-success setup-pass-page"><?= $this->translate('tr_melis_installer_common_next'); ?></a>
            </div>
        </div>
    </div>

</div>
