<!-- STEP 3 -->
<div class="item">
	<div class="setup-content-container">
	
		<div class="setup-heading">
			<h2><?= $this->translate('tr_melis_installer_platform_init'); ?></h2> 
			<p><?= $this->translate('tr_melis_installer_platform_init_subtext'); ?></p>	
		</div>
    	
    	<div class="setup-content setup-p3">
    	
			<div class="row">

				
					<div class="col-xs-12 col-md-6">
						
						<h4 class="no-padding-top border-bottom"><?= $this->translate('tr_melis_installer_platform_init_create_user'); ?></h4>
						<?php 
            				$form = $this->setup3_createUserForm;
            				echo $this->form()->openTag($form);
            				echo $this->melisFieldCollection($form);
            				echo $this->form()->closeTag();
        				?>


					</div>
					
					<?php 
					if($this->setup3_hasMelis): ?>
					<div class="col-xs-12 col-md-6">
						<?php 
						if(!is_null($this->setup3_webLangForm)) {
						    echo '<h4 class="no-padding-top border-bottom">'.$this->translate('tr_melis_installer_platform_init_sel_language').'</h4>';
						    $form = $this->setup3_webLangForm;
						    echo $this->form()->openTag($form);
						    echo $this->melisFieldCollection($form);
						    echo $this->form()->closeTag();
						}
						
						if(!is_null($this->setup3_webForm)) {
						    echo '<h4 class="border-bottom">'.$this->translate('tr_melis_installer_platform_init_create_web').'</h4>';
						    $form = $this->setup3_webForm;
						    $siteName = $form->get('website_name');
						    $siteModule = $form->get('website_module');
						    if(!$siteName->getValue()) {
						        $siteName->setValue(getenv('MELIS_MODULE'));
						    }
						    if(!$siteModule->getValue()) {
						        $siteModule->setValue(getenv('MELIS_MODULE')); 
						    }
						    echo $this->form()->openTag($form);
						    echo $this->melisFieldCollection($form);
						    echo $this->form()->closeTag();
						}
						?>
					</div>
					<?php endif; ?>
			</div>


	    	<div class="setup-button-cont">
     			<a class="btn btn-success setup-pass-page"><?= $this->translate('tr_melis_installer_common_next'); ?></a>
     		</div>
    	</div>
		
	</div>
</div>