<!-- STEP 3.1 -->
<div class="item">
	<div class="setup-content-container">
		<div class="setup-heading">
			<h2><?= $this->translate('tr_melis_installer_web_config'); ?></h2> 
			<p><?= $this->translate('tr_melis_installer_web_config_subtext'); ?></p>
		</div>
    	<div class="setup-content setup-p3" id="setup-step3" style="margin-top: 0px;">
			<?php if($this->setup3_hasMelis){ ?>
				<div class="row">
					<div class="col-xs-12">
    					<?php 
        					$form = $this->setup3_webConfigOption;
        					echo $this->form()->openTag($form);
        					$webOption = $form->get('weboption')->getValue();
        				?>
        					<ul class="list-group">
                                <li class="list-group-item">
                                	<div class="font-awesome-radio-container pull-left">
                            			<input id="weboption-none" type="radio" class="font-awesome-radio weboption-radio" name="weboption" value="None" <?= ($webOption == 'None') ? 'checked' : ''?>>
                            			<label for="weboption-none"></label>
                        			</div>
                                	<?= $this->translate('tr_melis_installer_option_none'); ?>
                            	</li>
                                <li class="list-group-item">
                                	<div class="font-awesome-radio-container pull-left">
                            			<input id="weboption-newsite" type="radio" class="font-awesome-radio weboption-radio" name="weboption" value="NewSite" <?= ($webOption == 'NewSite')? 'checked' : ''?>>
                            			<label for="weboption-newsite"></label>
                        			</div>
                                	<?= $this->translate('tr_melis_installer_option_new_website'); ?>
                            	</li>
                                <li class="list-group-item">
                                	<div class="font-awesome-radio-container pull-left">
                            			<input id="weboption-democms" type="radio" class="font-awesome-radio weboption-radio" name="weboption" value="MelisDemoCms" <?= ($webOption == 'MelisDemoCms' || empty($webOption)) ? 'checked' : ''?>>
                            			<label for="weboption-democms"></label>
                        			</div>
                            		<?= $this->translate('tr_melis_installer_option_use_demo_cms'); ?>
                        		</li>
                            </ul>
                        <?php 
    				        echo $this->form()->closeTag();
					    ?>
    				</div>
    			</div>
    			<br>
    			<div class="row">
					<div class="col-xs-12 col-md-6">
						<div class="setup3-webform <?php echo (!$this->setup3_showWebForm) ? 'hidden' : '' ?>">
							<h4 class="border-bottom"><?php echo $this->translate('tr_melis_installer_web_config_create_web_sel_language')?></h4>
							<?php 
    							$form = $this->setup3_webLangForm;
    							echo $this->form()->openTag($form);
    							echo $this->melisFieldCollection($form);
    							echo $this->form()->closeTag();
        							
						        $form = $this->setup3_webForm;
						        $siteName = $form->get('website_name');
						        $siteModule = $form->get('website_module');
						        if(!$siteName->getValue()) {
						            $siteName->setValue(getenv('MELIS_MODULE'));
						        }
						        if(!$siteModule->getValue()) {
						            $siteModule->setValue(getenv('MELIS_MODULE'));
						        }
						        echo $this->form()->openTag($form);
						        echo $this->melisFieldCollection($form);
						        echo $this->form()->closeTag();
    						?>
						</div>
					</div>
				</div>
			<?php } ?>
	    	<div class="setup-button-cont">
     			<a class="btn btn-success setup-pass-page"><?= $this->translate('tr_melis_installer_common_next'); ?></a>
     		</div>
    	</div>
	</div>
</div>