<!-- STEP 3.2 -->
<div class="item">
	<div class="setup-content-container">
		<div class="setup-heading">
			<h2><?= $this->translate('tr_melis_installer_melis_config'); ?></h2> 
			<p><?= $this->translate('tr_melis_installer_melis_config_subtext'); ?></p>	
		</div>
    	<div class="setup-content setup-p3">
			<div class="row">
				<div class="col-xs-12 col-md-6">
					<h4 class="no-padding-top border-bottom"><?= $this->translate('tr_melis_installer_melis_config_create_admin'); ?></h4>
					<?php 
        				$form = $this->setup3_createUserForm;
        				echo $this->form()->openTag($form);
        				echo $this->melisFieldCollection($form);
        				echo $this->form()->closeTag();
    				?>
				</div>
			</div>
	    	<div class="setup-button-cont">
     			<a class="btn btn-success setup-pass-page"><?= $this->translate('tr_melis_installer_common_next'); ?></a>
     		</div>
    	</div>
	</div>
</div>