			<!-- CREATION & RESULT -->
		    <div class="item">
				<div class="setup-content-container">
		    	
		    		<div class="setup-heading">
		    			<h2><?= $this->translate('tr_melis_installer_creation_result'); ?></h2> 
	      				<p><?= $this->translate('tr_melis_installer_creation_result_subtext'); ?></p>	
		    		</div>
			    	
			    	<div class="setup-content setup-creation">

				    	<div class="setup-button-cont">
			     			<a class="btn btn-success setup-pass-page setup-finish"><?= $this->translate('tr_melis_installer_common_finish'); ?></a> 
			     		</div>
			    	</div>
	      			
	     		</div>
			</div>