<!-- STEP 2.1 -->
<div class="item">
	<div class="setup-content-container">
	
		<div class="setup-heading">
			<h2><?= $this->translate('tr_melis_installer_layout_modules'); ?></h2> 
			<p><?= $this->translate('tr_melis_installer_layout_modules_subtext'); ?></p>	
		</div>
		
		<div class="setup-content setup-p2">
    		<div class="row">
	    		<div class="col-xs-12 col-md-6">
					<h2> <?= $this->translate('tr_melis_installer_layout_module_available'); ?></h2>

					  <form role="form" id="frmSelModules">
					  <?php foreach($this->setup2_1_modules as $modules):?>
						
						<?php if(in_array($modules, $this->setup2_1_selected)) {?>
                        <div class="checkbox">
                          	
                          	<div class="checkbox cb-cont" style="position:relative">
                               <label class="remember-me-cont">
                                    <span class="cbmask-outer clearfix">
                                    	<span  class="cbmask-inner"></span>
                                   	</span>
                                    <input type="checkbox" name="chk<?= $modules; ?>" value="<?= $modules; ?>" checked>
                               </label>
                               <span class="module-name"><?= $modules; ?></span>
                            </div>
                         
                        </div>
                        <?php }else { ?>
                        <div class="checkbox">
                         
                          	 <div class="checkbox cb-cont" style="position:relative">
                               <label class="remember-me-cont">
                                    <span class="cbmask-outer clearfix">
                                    	<span  class="cbmask-inner"></span>
                                   	</span>
                                    <input type="checkbox" value="<?= $modules; ?>" name="chk<?= $modules; ?>" >
                               </label>
                               <span class="module-name"><?= $modules; ?></span>
                            </div>
                          
                        </div>
  

                      <?php } endforeach; ?>
                      </form>
                      <br/>
					<form role="form" id="frmSelector">
						<div class="checkbox">
                          	 <div class="checkbox cb-cont" style="position:relative">
                               <label class="remember-me-cont">
                                    <span class="cbmask-outer clearfix">
                                    	<span class="cbmask-inner"></span>
                                   	</span>
                                    <input type="checkbox" id="chkSelectAllModules">
                               </label>
                               <span class="module-name"><?= $this->translate('tr_melis_installer_layout_module_select_all'); ?></span>
                            </div>
                        </div>
					</form>
					<div class="setup-button-cont">
		     			<a id="dbNext" class="setup-pass-page btn btn-success"><?= $this->translate('tr_melis_installer_common_next'); ?></a>
		     		</div>
	    		</div>
    		</div> 
    	</div>
	</div>
</div>