<div class="environment-cont entry">
    <div class="form-group">
        <label><?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?> <a class="btn btn-danger pull-right"><i class="fa fa-trash-o" aria-hidden="true"></i> <?= $this->translate('tr_melis_installer_layout_env_remove'); ?></a></label>
        <input type="text" class="form-control" placeholder="<?= $this->translate('tr_melis_installer_Layout_env_env_name'); ?>" name="environment_name_<?= $this->count; ?>" required>
    </div>
    <div class="form-group">
        <label><?= $this->translate('tr_melis_installer_layout_env_back_office_domain'); ?></label>
        <input type="url" class="form-control" placeholder="<?= $this->translate('tr_melis_installer_layout_env_back_office_domain'); ?>" name="domain_<?= $this->count; ?>" required>
    </div>
	
	<div class="form-group">
        <label><?= $this->translate('tr_melis_installer_layout_env_advance_parameters'); ?> <i class="fa fa-plus pull-right melis-install-adv-prop-trigger" aria-hidden="true" title="Tooltip on left"></i></label>
    </div>
    <div class="melis-install-adv-prop-content">
        <div class="form-group">
            <label><?= $this->translate('tr_melis_installer_layout_env_send_email'); ?></label>
            <div  class="make-switch module-switch" data-on-label="<?= $this->translate('tr_melis_installer_layout_env_send_email_enabled'); ?>" data-off-label="<?= $this->translate('tr_melis_installer_layout_env_send_email_disabled'); ?>" data-text-label="<?= $this->translate('tr_melis_installer_common_status'); ?>">
                <input name="send_email_<?= $this->count; ?>" data-module-name="" type="checkbox"/>
            </div>
        </div>
        <div class="form-group">
            <label><?= $this->translate('tr_melis_installer_layout_env_error_reporting'); ?></label>
            <select name="error_reporting_<?= $this->count; ?>" class="form-control">
                <option value="E_ALL & ~E_USER_DEPRECATED"><?= $this->translate('tr_melis_installer_layout_env_error_reporting_all'); ?></option>
                <option value="0"><?= $this->translate('tr_melis_installer_layout_env_error_reporting_off'); ?></option>
            </select>
        </div>
    </div>
</div>