<!--breadcumb area start -->
<?php 
    $subject = $this->MelisTag($this->idPage, 'header_image', 'media', '');
    preg_match('/<img\s.*?\bsrc="(.*?)".*?>/si', $subject, $matches);
    
    $imgSrc = '/MelisDemoCms/images/bg/designs.jpg';
    if (!empty($matches[1]))
    {
        $imgSrc = $matches[1];
    }
    $imgBg = 'background: rgba(0, 0, 0, 0) url('.$imgSrc.') no-repeat scroll 0 0';
?>

<div class="breadcumb-area overlay pos-rltv" style="<?php echo $imgBg ?>">
	<?php if ($this->renderMode == 'melis'):?>
    	<div class="breadcumb-area-overlay-media">
    		<?php echo $this->MelisTag($this->idPage, 'header_image', 'media', '<img alt="" src="'.$imgSrc.'">');?>
    	</div>
	<?php endif;?>
    <div class="bread-main">
        <div class="bred-hading text-center">
            <h5><?php echo $this->MelisTag($this->idPage, 'header_title', 'textarea', 'Our Designs')?></h5> 
        </div>
    	<?php echo $this->layout()->pageBreadcrumb?>
    </div>
</div>
<!--breadcumb area end -->

<div class="col-xs-12 text-center">
    <div class="heading-title heading-style pos-rltv mtb-50 text-center">
        <h5 class="uppercase"><?php echo $this->MelisTag($this->idPage, 'header_subtitle', 'textarea', 'Brand Product')?></h5> 
    </div>
</div>

<!--single blog main area are start-->
<div class="shop-main-area pt-70 pb-40">
    <div class="container">
        <div class="show-product single row">
        	<div class="col-xs-12">
        		<?php echo $this->MelisDragDropZone($this->idPage, "dragdropzone_detail_1") ?>
        	</div>
            <div class="col-lg-7 col-md-6 col-sm-6 col-xs-12">
                <div class="brand-img text-center">
                    <?php echo $this->MelisTag($this->idPage, 'content_image', 'media', '<img src="/MelisDemoCms/images/team/branding.png" alt="">')?>
                </div>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                <div class="show-product-description">
                    <h6 class="sp-category"><?php echo $this->MelisTag($this->idPage, 'content_subtitle1', 'textarea', 'New Fashion')?></h6>
                    <h2 class="uppercase montserrat"><?php echo $this->MelisTag($this->idPage, 'content_title', 'textarea', 'Brand Cortta')?></h2>
                    <div class="product-price-cont">
                        <span class="product-price"><?php echo $this->MelisTag($this->idPage, 'content_subtitle2', 'textarea', '$200')?></span>
                    </div>
                    <?php 
                        echo $this->MelisTag($this->idPage, 'content_text', 'html', 
                        '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum</p>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>')
                    ?>
                </div>
            </div>
        </div>  
    </div>
</div>