<!--breadcumb area start -->
<?php 
    $subject = $this->MelisTag($this->idPage, 'header_image', 'media', '');
    preg_match('/<img\s.*?\bsrc="(.*?)".*?>/si', $subject, $matches);
    
    $imgSrc = '/MelisDemoCms/images/bg/designs.jpg';
    if (!empty($matches[1]))
    {
        $imgSrc = $matches[1];
    }
    $imgBg = 'background: rgba(0, 0, 0, 0) url('.$imgSrc.') no-repeat scroll 0 0';
?>

<div class="breadcumb-area overlay pos-rltv" style="<?php echo $imgBg ?>">
	<?php if ($this->renderMode == 'melis'):?>
    	<div class="breadcumb-area-overlay-media">
    		<?php echo $this->MelisTag($this->idPage, 'header_image', 'media', '<img alt="" src="'.$imgSrc.'">');?>
    	</div>
	<?php endif;?>
    <div class="bread-main">
        <div class="bred-hading text-center">
            <h5><?php echo $this->MelisTag($this->idPage, 'header_title', 'textarea', 'Our Designs')?></h5> 
        </div>
    	<?php echo $this->layout()->pageBreadcrumb?>
    </div>
</div>
<!--breadcumb area end -->

<div class="full-width row">
	<div class="col-xs-12 text-center">
        <div class="heading-title heading-style pos-rltv mtb-50 text-center">
            <h5 class="uppercase"><?php echo $this->MelisTag($this->idPage, 'content_subtitle', 'textarea', 'Shirts')?></h5> 
        </div>
    </div>
</div>

<!--single blog main area are start-->
<div class="shop-main-area pt-70 pb-40">
    <div class="container">
        <div class="row">
        	<div class="col-xs-12">
				<?php echo $this->MelisDragDropZone($this->idPage, "dragdropzone_content_1") ?>
			</div>
			<div class="col-xs-12">
            <?php 
                echo $this->MelisTag($this->idPage, 'content_text_1', 'html', 
                '<div class="show-product row">
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                        <div class="brand-img text-center">
                            <img src="/MelisDemoCms/images/product/01.jpg" alt="">
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12">
                        <div class="show-product-description">
                            <h6 class="sp-category">New Fashion</h6>
                            <h2 class="uppercase montserrat">Brand Cortta</h2>
                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum</p>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>                                
                        </div>
                    </div>
                </div>');
            ?>
        	</div>
        </div>
        <br>
        <div class="row">
			<div class="col-xs-12">
            <?php 
                echo $this->MelisTag($this->idPage, 'content_text_2', 'html',
                    '<div class="show-product row">
                    <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12">
                        <div class="show-product-description">
                            <h6 class="sp-category">New Fashion</h6>
                            <h2 class="uppercase montserrat">Brand Cortta</h2>
                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum</p>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                        <div class="brand-img text-center">
                            <img src="/MelisDemoCms/images/product/02.jpg" alt="">
                        </div>
                    </div>
                </div>');
            ?>
        	</div>
        </div>
        <br>
        <div class="row">
			<div class="col-xs-12">
            <?php 
                echo $this->MelisTag($this->idPage, 'content_text_3', 'html',
                    '<div class="show-product row">
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                        <div class="brand-img text-center">
                            <img src="/MelisDemoCms/images/product/03.jpg" alt="">
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12">
                        <div class="show-product-description">
                            <h6 class="sp-category">New Fashion</h6>
                            <h2 class="uppercase montserrat">Brand Cortta</h2>
                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum</p>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                        </div>
                    </div>
                </div>');
            ?>
        	</div>
        </div>
        <br>
        <div class="row">
			<div class="col-xs-12">
            <?php
                echo $this->MelisTag($this->idPage, 'content_text_4', 'html',
                    '<div class="show-product row">
                    <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12">
                        <div class="show-product-description">
                            <h6 class="sp-category">New Fashion</h6>
                            <h2 class="uppercase montserrat">Brand Cortta</h2>
                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum</p>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                        <div class="brand-img text-center">
                            <img src="/MelisDemoCms/images/product/04.jpg" alt="">
                        </div>
                    </div>
                </div>');
            ?>
        	</div>
        </div>
        <br>
        <div class="row">
			<div class="col-xs-12">
            <?php
                echo $this->MelisTag($this->idPage, 'content_text_5', 'html',
                    '<div class="show-product row">
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                        <div class="brand-img text-center">
                            <img src="/MelisDemoCms/images/product/05.jpg" alt="">
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12">
                        <div class="show-product-description">
                            <h6 class="sp-category">New Fashion</h6>
                            <h2 class="uppercase montserrat">Brand Cortta</h2>
                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum</p>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                        </div>
                    </div>
                </div>');
            ?>
        	</div>
        </div>
        <br>
        <div class="row">
			<div class="col-xs-12">
            <?php
                echo $this->MelisTag($this->idPage, 'content_text_6', 'html',
                    '<div class="show-product row">
                    
                    <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12">
                        <div class="show-product-description">
                            <h6 class="sp-category">New Fashion</h6>
                            <h2 class="uppercase montserrat">Brand Cortta</h2>
                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum</p>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                        <div class="brand-img text-center">
                            <img src="/MelisDemoCms/images/product/06.jpg" alt="">
                        </div>
                    </div>
                </div>');
            ?>
            </div>
        </div>
    </div>
</div>