<div class="skill-content">
    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </p>
    <div class="powerfull-skills">
        <div class="single-prograss">
            <div class="progess-heading"> Photoshop <span>(79%)</span> </div>
            <div class="progress">
                <div class="progress-bar pr-blue wow fadeInLeft" style="width:79%" data-wow-duration="2s" data-wow-delay="1s"> </div>
            </div>
        </div>
        <div class="single-prograss">
            <div class="progess-heading"> Illustrator <span>(96%)</span> </div>
            <div class="progress">
                <div class="progress-bar pr-green wow fadeInLeft" style="width:96%" data-wow-duration="2s" data-wow-delay="1s"> </div>
            </div>
        </div>
        <div class="single-prograss">
            <div class="progess-heading pr-voilate"> HTML <span>(85%)</span> </div>
            <div class="progress">
                <div class="progress-bar pr-violate wow fadeInLeft" style="width:85%" data-wow-duration="2s" data-wow-delay="1s"> </div>
            </div>
        </div>
        <div class="single-prograss">
            <div class="progess-heading"> Wordpress <span>(92%)</span> </div>
            <div class="progress">
                <div class="progress-bar pr-ornage wow fadeInLeft" style="width:92%" data-wow-duration="2s" data-wow-delay="1s"> </div>
            </div>
        </div>
    </div>
    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. will be distracted by the readable content of a page when looking at its layout. </p>
</div>