<ul>
    <li>
        <div class="contact-icon"> 
        	<i class="zmdi zmdi-pin-drop"></i>
    	</div>
        <div class="contact-text">
            <p><span>777/a  Seventh Street,</span> <span>Rampura, Bonosri</span></p>
        </div>
    </li>
    <li>
        <div class="contact-icon"> <i class="zmdi zmdi-email-open"></i> </div>
        <div class="contact-text">
            <p><span><a href="#">company@gmail.com</a></span> <span><a href="#">admin@devitems.com</a></span></p>
        </div>
    </li>
    <li>
        <div class="contact-icon"> <i class="zmdi zmdi-phone-paused"></i> </div>
        <div class="contact-text">
            <p><span>+11 (019) 25184203</span> <span>+11 (018) 50950555</span></p>
        </div>
    </li>
</ul>