<div class="show-product row">
    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
        <div class="brand-img text-center">
            <img src="/MelisDemoCms/images/product/01.jpg" alt="">
        </div>
    </div>
    <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12">
        <div class="show-product-description">
            <h6 class="sp-category">New Fashion</h6>
            <h2 class="uppercase montserrat">Brand Cortta</h2>
            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum</p>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>                                
        </div>
    </div>
</div>