<div class="delivery-service-area ptb-30">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="single-service shadow-box text-center">
                    <img src="/MelisDemoCms/images/icons/garantee.png" alt="">
                    <h5>Money Back Guarantee</h5>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="single-service shadow-box text-center">
                    <img src="/MelisDemoCms/images/icons/coupon.png" alt="">
                    <h5>Gift Coupon</h5>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="single-service shadow-box text-center">
                    <img src="/MelisDemoCms/images/icons/delivery.png" alt="">
                    <h5>Free Shipping</h5>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="single-service shadow-box text-center">
                    <img src="/MelisDemoCms/images/icons/support.png" alt="">
                    <h5>24x7 Support</h5>
                </div>
            </div>
        </div>
    </div>
</div>