<div class="blockqot mtb-30">
    <blockquote>
    	<p>There are many variations of passages of Lorem Ipsum available, 
    	but majority have suffered alteration in some form, by injected humour. 
    	There are many variations of passages of Lorem Ipsum available, 
    	but the majorit. There are many variations of passages of Lorem 
    	Ipsum available, but the majorit.
    	</p>
	</blockquote>
</div>