<div class="blog-title">
    <h5 class="uppercase font-bold">New fashion collection 2016</h5>
    <div class="blog-text">
        <p>There are many variations of passages of Lorem Ipsum available, but the majority suffered alteration in some form, 
        	by injected humour, or random ised words which don't look even slightly believable. If you are going to use a passage 
        	of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum. 
            <br>
            <br>
            generators on the Internet tend to repeat predefined chunks as necessary. 
            There are many variations of passages of Lorem Ipsum available the Internet tend to repeat 
            predefined chunks as necessary. There are many variations of passages of Lorem Ipsum available
        </p>
    </div>
</div>