<!--breadcumb area start -->
<?php 
    $subject = $this->MelisTag($this->idPage, 'header_image', 'media', '');
    preg_match('/<img\s.*?\bsrc="(.*?)".*?>/si', $subject, $matches);
    
    $imgSrc = '/MelisDemoCms/images/bg/news.jpg';
    if (!empty($matches[1]))
    {
        $imgSrc = $matches[1];
    }
    $imgBg = 'background: rgba(0, 0, 0, 0) url('.$imgSrc.') no-repeat scroll 0 0';
?>

<div class="breadcumb-area overlay pos-rltv" style="<?php echo $imgBg ?>">
	<?php if ($this->renderMode == 'melis'):?>
    	<div class="breadcumb-area-overlay-media">
    		<?php echo $this->MelisTag($this->idPage, 'header_image', 'media', '<img alt="" src="'.$imgSrc.'">');?>
    	</div>
	<?php endif;?>
    <div class="bread-main">
        <div class="bred-hading text-center">
            <h5><?php echo $this->MelisTag($this->idPage, 'header_title', 'textarea', 'News')?></h5> 
        </div>
    	<?php echo $this->layout()->pageBreadcrumb?>
    </div>
</div>
<!--breadcumb area end -->

<!--blog area are start-->
<div class="blog-area pb-70">
    <div class="container">
    	
    	<div class="filter-top">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-sm-push-6 col-md-4 col-md-push-8">
                   <!--single search start-->
                    <div class="single-aside search-aside search-box">
                        <form action="" method="get">
                            <div class="input-box">
                                <input class="single-input" name="search-news" placeholder="Search News...." type="text" value="<?php echo $this->layout()->searchNews ?>">
                                <button class="src-btn sb-2"><i class="fa fa-search"></i></button>
                            </div>
                        </form>
                     </div>
                    <!--single search end-->
                </div>
                <div class="col-xs-12 col-sm-6 col-sm-pull-6 col-md-8 col-md-pull-4">
                    <div class="sort date-filter">
                        <label>Sort By: </label>
                        <select onchange="location = this.value">
                        	<?php $selected = 'selected'?>
                        	<?php if (!empty($this->layout()->searchNews)):?>
                        		<option selected value=""></option>
                        		<?php $selected = ''?>
                        	<?php endif;?>
                        	<option <?php echo $selected?> value="<?php echo $this->MelisLink($this->idPage, true)?>">-- All --</option>
                            <?php 
                                foreach ($this->list As $key => $val)
                                {
                                    $options =  '<optgroup label="'.$val['text'].'">';
                                    foreach ($val['options'] As $oKey => $oVal)
                                    {
                                        // Setting the Selected option
                                        $selected = '';
                                        if ($oVal['selected'])
                                        {
                                            $selected = 'selected';
                                        }
                                        $options .=  '<option '.$selected.' value="'.$this->MelisLink($this->idPage, false).'?datefilter='.$oVal['opt-data']['datefilter'].'">'.$oVal['text'].'</option>';
                                    }
                                    $options .=  '</optgroup>';
                                    echo $options;
                                }
                            ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        
        <!--Total area start-->
        <div class="col-xs-12 text-center">
            <div class="heading-title heading-style pos-rltv mtb-50 text-center">
                <h5 class="uppercase"><?php echo $this->MelisTag($this->idPage, 'header_subtitle', 'textarea', 'News')?></h5> 
            </div>
        </div>
        
        <div class="clearfix"></div>
        
        <!-- List of News start -->
        <?php echo $this->listNews ?>
        <!-- End of List of News -->
    </div>
</div>
<!--blog area are end-->