<!--breadcumb area start -->
<?php 
    $subject = $this->MelisTag($this->idPage, 'header_image', 'media', '');
    preg_match('/<img\s.*?\bsrc="(.*?)".*?>/si', $subject, $matches);
    
    $imgSrc = '/MelisDemoCms/images/bg/contact.jpg';
    if (!empty($matches[1]))
    {
        $imgSrc = $matches[1];
    }
    $imgBg = 'background: rgba(0, 0, 0, 0) url('.$imgSrc.') no-repeat scroll 0 0';
?>

<div class="breadcumb-area overlay pos-rltv" style="<?php echo $imgBg ?>">
	<?php if ($this->renderMode == 'melis'):?>
    	<div class="breadcumb-area-overlay-media">
    		<?php echo $this->MelisTag($this->idPage, 'header_image', 'media', '<img alt="" src="'.$imgSrc.'">');?>
    	</div>
	<?php endif;?>
    <div class="bread-main">
        <div class="bred-hading text-center">
            <h5><?php echo $this->MelisTag($this->idPage, 'header_title', 'textarea', 'About Us')?></h5> 
        </div>
    	<?php echo $this->layout()->pageBreadcrumb?>
    </div>
</div>
<!--breadcumb area end -->

<!--map area start-->
<div class="map-area">
    <div id="googleMap"></div>
    <div class="google-map-overlay-inputs" style="<?php echo ($this->renderMode == 'melis') ? 'position: absolute; right: 100px;' : 'display : none'?>">
    	<div class="row">
        	<div class="col-xs-6" id="about-us-latitude">
        		<?php 
        		    echo $this->MelisTag($this->idPage, 'contact_gmap_lat', 'textarea', '10.2963459');
        		?>
        	</div>
        	<div class="col-xs-6" id="about-us-longitude">
        		<?php 
        		    echo $this->MelisTag($this->idPage, 'contact_gmap_long', 'textarea', '123.896545');
        		?>
        	</div>
    	</div>
    </div>
</div>
<!--map area end-->

<!--contact info are start-->
<div class="contact-info ptb-70">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6">
            	<?php echo $this->prospectsForm?>
            </div>
            <div class="col-md-6 col-sm-6">
            	<div class="single-footer contact-us contact-us-2">
                	<?php echo $this->MelisTag($this->idPage, 'contact_addresses', 'html',
                        '<div class="heading-title text-center mb-50">
                            <h5 class="uppercase">Contact Info</h5> 
                            </div>
                        <ul class="contact-info">
                            <li>
                                <div class="contact-icon"> <i class="zmdi zmdi-phone-paused"></i> </div>
                                <div class="contact-text">
                                    <p><span>+11 (019) 25184203</span> <span>+11 (018) 50950555</span></p>
                                </div>
                            </li>
                            <li>
                                <div class="contact-icon"> <i class="zmdi zmdi-email-open"></i> </div>
                                <div class="contact-text">
                                    <p><span><a href="#">company@gmail.com</a></span> <span><a href="#">admin@devitems.com</a></span></p>
                                </div>
                            </li>
                            <li>
                                <div class="contact-icon"> <i class="zmdi zmdi-pin-drop"></i> </div>
                                <div class="contact-text">
                                    <p><span>777, Seventh Streeth, Rampura,</span> <span>Dhaka, Bangladesh</span></p>
                                </div>
                            </li>
                        </ul>')
            	    ?>
        	    	<div class="social-icon-wraper mt-25">
                        <div class="social-icon socile-icon-style-1">
                            <ul>
                                <li><a href="https://www.facebook.com/melistechnology" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
                                <li><a href="https://twitter.com/meliscms" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
                                <li><a href="https://www.linkedin.com/company/melis-technology" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
               <div class="pos-rltv">
               		<div class="contact-des">
                        <?php echo $this->MelisTag($this->idPage, 'contact_text', 'html',
                            '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. 
                            The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', 
                            making it look like readable English.</p>')
                	    ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--contact info are end-->