<!--breadcumb area start -->
<?php 
    $subject = $this->MelisTag($this->idPage, 'header_image', 'media', '');
    preg_match('/<img\s.*?\bsrc="(.*?)".*?>/si', $subject, $matches);
    
    $imgSrc = '/MelisDemoCms/images/bg/about.jpg';
    if (!empty($matches[1]))
    {
        $imgSrc = $matches[1];
    }
    $imgBg = 'background: rgba(0, 0, 0, 0) url('.$imgSrc.') no-repeat scroll 0 0';
?>

<div class="breadcumb-area overlay pos-rltv" style="<?php echo $imgBg ?>">
	<?php if ($this->renderMode == 'melis'):?>
    	<div class="breadcumb-area-overlay-media">
    		<?php echo $this->MelisTag($this->idPage, 'header_image', 'media', '<img alt="" src="'.$imgSrc.'">');?>
    	</div>
	<?php endif;?>
    <div class="bread-main">
        <div class="bred-hading text-center">
            <h5><?php echo $this->MelisTag($this->idPage, 'header_title', 'textarea', 'Our Designs')?></h5> 
        </div>
    	<?php echo $this->layout()->pageBreadcrumb?>
    </div>
</div>
<!--breadcumb area end -->

<!-- about-us-area start-->
<div class="about-us-area ptb-70">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-center">
                <div class="heading-title heading-style pos-rltv mb-50 text-center">
                    <h5 class="uppercase"><?php echo $this->MelisTag($this->idPage, 'about_part1_title', 'textarea', 'About Us')?></h5>
                </div>
            </div>
            <div class="col-xs-12">
            	<?php echo $this->MelisDragDropZone($this->idPage, "dragdropzone_about_1") ?>
            	<?php echo $this->MelisDragDropZone($this->idPage, "dragdropzone_about_2") ?>
            </div>
            <div class="about-us-wrap">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <div class="about-img">
                   		<?php echo $this->MelisTag($this->idPage, 'about_part1_image', 'media', '<img src="/MelisDemoCms/images/blog/about01.jpg" alt="">')?>
                   	</div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                	<?php 
                    	echo $this->MelisTag($this->idPage, 'about_part1_text', 'html', 
                	    '<div class="about-des">
                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English.</p>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </p>
                        </div>')
            	    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- about-us-area end-->

<!--choose us area start-->
<div class="choose-us-area pb-70">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-center">
                <div class="heading-title heading-style pos-rltv mb-50 text-center">
                    <h5 class="uppercase"><?php echo $this->MelisTag($this->idPage, 'about_part2_title', 'textarea', 'Why choose us')?></h5>
                </div>
            </div>
        </div>
        <div class="row">
            <?php 
                echo $this->MelisTag($this->idPage, 'about_part2_text', 'html',
                    '<div class="col-md-3 col-sm-4 col-xs-12">
                        <div class="single-choose text-center">
                            <div class="choose-icon pos-rltv">
                            	<div class="svg">
                                	<svg class="svg-star" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                    	viewBox="0 0 42 50" enable-background="new 0 0 42 50" xml:space="preserve">
                                    <g>
                                    	<path fill="#262826" d="M11.1,40.8c0,0,3.3,1.4,4.7-1.2C15.8,39.6,13.5,37.9,11.1,40.8z"/>
                                    	<path fill="#262826" d="M13.5,35.9c-0.2,1.9,1.1,2.8,1.1,2.8c0.7,0,1.3,0.5,1.3,0.5C16.3,36.7,13.5,35.9,13.5,35.9z"/>
                                    	<path fill="#262826" d="M7.5,38.1c0,0,2.6,2.1,4.8,0.2C12.3,38.3,10.6,35.9,7.5,38.1z"/>
                                    	<path fill="#262826" d="M11.3,37.2c0.8,0.2,1.1,0.8,1.1,0.8C13.7,35.6,11,34,11,34C10.4,35.7,11.3,37.2,11.3,37.2z"/>
                                    	<path fill="#262826" d="M9.3,35.9c0,0-1.4-2.7-4.8-1C4.4,35,6.8,37.5,9.3,35.9z"/>
                                    	<path fill="#262826" d="M8.7,31.6c-1,1.5-0.3,3-0.3,3c0.8,0.4,1.1,1,1.1,1C10.9,33.5,8.7,31.6,8.7,31.6z"/>
                                    	<path fill="#262826" d="M6.5,33.1c0,0-0.8-2.9-4.4-2.1C2.1,31.1,3.8,34.1,6.5,33.1z"/>
                                    	<path fill="#262826" d="M6.8,32.9c2-1.7,0.3-4.1,0.3-4.1c-1.4,1.3-1,2.9-1,2.9C6.7,32.3,6.8,32.9,6.8,32.9z"/>
                                    	<path fill="#262826" d="M4.7,30.1c0,0,0.2-2.9-3.6-3.2C1.1,26.9,1.9,30.3,4.7,30.1z"/>
                                    	<path fill="#262826" d="M6.5,26.1c-1.7,0.9-1.8,2.5-1.8,2.5C5.1,29.4,5.1,30,5.1,30C7.5,28.9,6.5,26.1,6.5,26.1z"/>
                                    	<path fill="#262826" d="M3.3,26.4c0,0,0.6-2.9-3.1-3.8C0.2,22.6,0.4,26.1,3.3,26.4z"/>
                                    	<path fill="#262826" d="M5.6,22.6c-1.8,0.7-2.1,2.3-2.1,2.3c0.3,0.8,0.2,1.5,0.2,1.5C6.2,25.7,5.6,22.6,5.6,22.6z"/>
                                    	<path fill="#262826" d="M3,22.5c0,0,1.1-2.8-2.4-4.3C0.7,18.1,0.3,21.5,3,22.5z"/>
                                    	<path fill="#262826" d="M6,19.2c-1.8,0.3-2.5,1.8-2.5,1.8c0.2,0.8-0.1,1.4-0.1,1.4C6,22.1,6,19.2,6,19.2z"/>
                                    	<path fill="#262826" d="M3.2,18.5c0,0,1.8-2.4-1.3-4.7C1.9,13.8,0.7,17,3.2,18.5z"/>
                                    	<path fill="#262826" d="M6.9,16.1C5,15.9,4,17.2,4,17.2c0,0.8-0.5,1.4-0.5,1.4C6.1,19,6.9,16.1,6.9,16.1z"/>
                                    	<path fill="#262826" d="M11.5,7.3c0,0-5.1,0.5-5.5,4.7C6,12.1,10.4,12.9,11.5,7.3z"/>
                                    	<path fill="#262826" d="M4,10.1c0,0-1.9,2.9,0.1,4.8C4.2,14.9,6.5,13,4,10.1z"/>
                                    	<path fill="#262826" d="M4.6,15.1c2.4,1.1,3.7-1.6,3.7-1.6c-1.7-0.6-3,0.4-3,0.4C5,14.7,4.6,15.1,4.6,15.1z"/>
                                    	<path fill="#262826" d="M26.1,39.6c1.5,2.5,4.7,1.2,4.7,1.2C28.5,37.9,26.1,39.6,26.1,39.6z"/>
                                    	<path fill="#262826" d="M28.5,35.9c0,0-2.9,0.7-2.4,3.4c0,0,0.5-0.5,1.3-0.5C27.4,38.8,28.6,37.9,28.5,35.9z"/>
                                    	<path fill="#262826" d="M29.6,38.3c2.2,1.9,4.9-0.2,4.9-0.2C31.4,35.9,29.6,38.3,29.6,38.3z"/>
                                    	<path fill="#262826" d="M29.4,38c0,0,0.4-0.6,1.2-0.8c0,0,0.9-1.4,0.2-3.1C30.8,34,28.2,35.6,29.4,38z"/>
                                    	<path fill="#262826" d="M32.7,35.9c2.5,1.6,4.9-1,4.9-1C34.1,33.3,32.7,35.9,32.7,35.9z"/>
                                    	<path fill="#262826" d="M32.5,35.6c0,0,0.3-0.6,1-1c0,0,0.7-1.5-0.2-3C33.3,31.6,30.9,33.5,32.5,35.6z"/>
                                    	<path fill="#262826" d="M35.5,33.1c2.8,1,4.4-2.1,4.4-2.1C36.1,30.2,35.5,33.1,35.5,33.1z"/>
                                    	<path fill="#262826" d="M35.2,32.9c0,0,0.1-0.6,0.7-1.2c0,0,0.3-1.7-1-2.9C34.9,28.8,33.1,31.2,35.2,32.9z"/>
                                    	<path fill="#262826" d="M37.2,30.1c2.9,0.2,3.5-3.2,3.5-3.2C37.1,27.2,37.2,30.1,37.2,30.1z"/>
                                    	<path fill="#262826" d="M35.5,26.1c0,0-1,2.8,1.4,3.9c0,0-0.1-0.6,0.4-1.4C37.2,28.6,37.1,27,35.5,26.1z"/>
                                    	<path fill="#262826" d="M38.7,26.4c2.8-0.3,3-3.8,3-3.8C38,23.5,38.7,26.4,38.7,26.4z"/>
                                    	<path fill="#262826" d="M36.4,22.6c0,0-0.7,3.1,1.9,3.8c0,0-0.1-0.7,0.1-1.5C38.4,24.9,38,23.3,36.4,22.6z"/>
                                    	<path fill="#262826" d="M39,22.5c2.7-0.9,2.3-4.3,2.3-4.3C37.8,19.7,39,22.5,39,22.5z"/>
                                    	<path fill="#262826" d="M38.4,20.9c0,0-0.7-1.5-2.5-1.8c0,0,0,2.9,2.5,3.2C38.5,22.4,38.3,21.7,38.4,20.9z"/>
                                    	<path fill="#262826" d="M38.8,18.5c2.5-1.5,1.2-4.7,1.2-4.7C37,16.1,38.8,18.5,38.8,18.5z"/>
                                    	<path fill="#262826" d="M38.4,18.6c0,0-0.4-0.6-0.4-1.4c0,0-1.1-1.3-2.9-1.1C35.1,16.1,35.8,19,38.4,18.6z"/>
                                    	<path fill="#262826" d="M36,12.1c-0.4-4.2-5.5-4.7-5.5-4.7C31.6,12.9,36,12.1,36,12.1z"/>
                                    	<path fill="#262826" d="M37.7,14.9c2.1-2,0.1-4.8,0.1-4.8C35.5,13,37.7,14.9,37.7,14.9z"/>
                                    	<path fill="#262826" d="M33.6,13.5c0,0,1.4,2.7,3.8,1.6c0,0-0.5-0.4-0.7-1.2C36.7,13.9,35.4,12.9,33.6,13.5z"/>
                                    	<polygon fill="#262826" points="21.8,38.5 21,36 20.2,38.5 17.6,38.5 19.7,40 18.8,42.5 21,41 23.1,42.5 22.2,40 24.4,38.5 	"/>
                                    	<path fill="#262826" d="M11.1,22v0.6v0.4c0.4,4.9,4.3,8.8,9.3,9.2l0.4,0.1h0.6l0.4-0.1c4.9-0.4,8.8-4.3,9.1-9.2l0.1-0.4v-0.5
                                    		l-0.1-0.4c-0.3-4.9-4.2-8.9-9.1-9.2h-0.4h-0.6h-0.4c-5,0.4-8.9,4.3-9.3,9.2V22z M11.9,22.1v-0.3c0.3-4.5,4-8.1,8.6-8.4l0.3,0h0.6
                                    		l0.3,0c4.6,0.3,8.2,4,8.5,8.4l0.1,0.3v0.5L30,23c-0.3,4.5-3.9,8.1-8.5,8.5h-0.3h-0.5h-0.3c-4.6-0.4-8.2-4-8.6-8.5v-0.3V22.1z"/>
                                    	<path fill="#262826" d="M20.5,30.6h0.3h0.4h0.4c4.1-0.2,7.4-3.6,7.6-7.7v-0.3v-0.5v-0.2c-0.2-4.1-3.5-7.4-7.6-7.7h-0.4h-0.4
                                    		l-0.3,0.1c-4.2,0.3-7.4,3.5-7.7,7.6l-0.1,0.2v0.5l0.1,0.3C13,27,16.3,30.4,20.5,30.6z M13.3,22.1v-0.3c0.3-3.8,3.4-6.9,7.2-7.1
                                    		l0.3,0h0.4l0.3,0c3.8,0.2,6.9,3.4,7.2,7.1l0.1,0.3v0.5l-0.1,0.3c-0.3,3.8-3.3,6.9-7.2,7.1h-0.3h-0.4h-0.3c-3.8-0.2-6.8-3.4-7.2-7.1
                                    		v-0.3V22.1z"/>
                                    	<polygon fill="#262826" points="17,28 21,25.1 25,28 23.6,23.3 27.4,20.5 22.6,20.5 21,15.7 19.4,20.5 14.6,20.5 18.5,23.3 	"/>
                                    </g>
                                    </svg>
                                </div>
                            </div>
                            <div class="choose-title">
                                <h5>High Quality</h5>
                            </div>
                            <div class="choose-des">
                               <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p> 
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-12">
                        <div class="single-choose text-center">
                            <div class="choose-icon pos-rltv">
                                <div class="svg">
                                    <svg version="1.1" class="svg-dollar" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                    	 viewBox="0 0 42 50" enable-background="new 0 0 42 50" xml:space="preserve">
                                    <g>
                                    	<path fill="#262826" d="M30.7,14.2C28.2,12,25,11,21.8,11c-4.2,0-8.2,1.8-11,5.2C8.4,19,7.2,22.7,7.6,26.4c0.3,3.6,2.1,7.1,5,9.5
                                    		c2.5,2.1,5.6,3.2,8.9,3.2c4.2,0,8.2-1.8,10.9-5.1c2.4-2.9,3.6-6.6,3.3-10.4C35.3,20,33.6,16.7,30.7,14.2z M33,25L33,25h-3.9
                                    		c-0.1,0-0.1,0-0.2,0c0,0,0,0-0.2,0h-0.5c-0.1,0-0.2,0.1-0.2,0.2c0,0.2,0.1,0.4,0.2,0.4h0.5c0.2,0,0.2,0,0.2-0.1
                                    		c0.2,0.1,0.2,0.1,0.2,0.1H33l0,0c-0.1,2.5-1,5-2.7,6.7c-2.2,2.8-5.4,4.4-8.9,4.4c-2.6,0-5.1-1-7.1-2.7c-2.2-1.9-3.7-4.6-4-7.5
                                    		c0-0.4,0-0.8,0-1.2H14c0.1,0,0.1,0,0.1-0.1c0.2,0.1,0.2,0.1,0.3,0.1h0.5c0.1,0,0.3-0.2,0.3-0.3c0,0-0.1-0.2-0.3-0.2h-0.5
                                    		c-0.1,0-0.1,0-0.3,0c0,0,0,0-0.1,0h-3.7c0-0.5,0.1-1,0.2-1.6c0.1,0.2,0.1,0.2,0.4,0.2h3.8c0,0,0.2,0,0.2,0c0.1,0,0.2,0,0.2,0h0.5
                                    		c0.2,0,0.2-0.1,0.2-0.2c0-0.2-0.1-0.3-0.2-0.3H15c0,0-0.1,0-0.2,0c0,0-0.2,0-0.2,0h-3.8c-0.2,0-0.3,0-0.3,0.1
                                    		c0.4-1.7,1.2-3.4,2.4-4.8c2.1-2.5,5.3-4.1,8.7-4.1c2.6,0,5.2,0.9,7.2,2.6c2.3,2,3.6,4.6,4,7.7C33,24.4,33,24.7,33,25z"/>
                                    	<path fill="#262826" d="M22.9,23.6c-1.7-0.7-2.4-1.1-2.4-1.5c0-0.7,0.6-1,1.6-1c1.3,0,2.1,0.5,2.7,0.7l0.2,0c0.1,0,0.2,0,0.2,0
                                    		c0.1,0,0.1-0.2,0.2-0.2l0.6-2.4c0,0,0-0.3-0.1-0.3c-0.9-0.4-1.9-0.7-2.9-0.7v-1.5c0-0.2-0.2-0.2-0.3-0.2h-2.1c-0.3,0-0.4,0-0.4,0.2
                                    		v1.7c-2.1,0.4-3.5,2-3.5,4c0,2.5,2.1,3.4,3.9,4.1c1.7,0.7,2.1,1.1,2.1,1.6c0,0.9-1.4,0.9-1.7,0.9c-1.5,0-2.7-0.5-3.3-0.9
                                    		c-0.1,0-0.2-0.1-0.3,0c-0.1,0.1-0.1,0.2-0.2,0.2l-0.7,2.4c0,0.2,0.1,0.3,0.2,0.3c0.8,0.5,2.1,0.8,3.4,0.9v1.8
                                    		c0,0.1,0.2,0.3,0.3,0.3h2c0.2,0,0.4-0.2,0.4-0.3v-1.9c2.2-0.5,3.7-2,3.7-4.1C26.6,25.7,25.5,24.4,22.9,23.6z"/>
                                    	<path fill="#262826" d="M15.5,26.4H15c-0.1,0-0.1,0-0.2,0.1c0-0.1-0.2-0.1-0.2-0.1h-3.8c-0.3,0-0.4,0.1-0.4,0.2
                                    		c0,0.2,0.2,0.4,0.4,0.4h3.8c0,0,0.2-0.1,0.2-0.1c0.1,0,0.1,0.1,0.2,0.1h0.4c0.3,0,0.3-0.1,0.3-0.4C15.8,26.4,15.7,26.4,15.5,26.4z"
                                    		/>
                                    	<path fill="#262826" d="M28.3,23c0,0-0.1,0-0.2,0h-0.5c-0.2,0-0.4,0.2-0.4,0.4c0,0.2,0.1,0.3,0.4,0.3h0.5c0.1,0,0.2,0,0.2,0
                                    		c0.1,0,0.1,0,0.2,0h3.8c0.1,0,0.3,0,0.3-0.3c0-0.2-0.2-0.4-0.3-0.4h-3.8C28.4,23,28.4,23,28.3,23z"/>
                                    	<path fill="#262826" d="M27.3,27c0,0.3,0.1,0.4,0.4,0.4h0.5c0.1,0,0.2-0.1,0.2-0.1c0.1,0,0.2,0.1,0.2,0.1h3.8
                                    		c0.2,0,0.3-0.1,0.3-0.4c0-0.1-0.1-0.3-0.3-0.3h-3.8c0,0-0.2,0-0.2,0.1c0-0.1-0.1-0.1-0.2-0.1h-0.5C27.4,26.7,27.3,26.8,27.3,27z"/>
                                    	<polygon fill="#262826" points="23.3,42.3 20.9,44 18.5,42.3 19.5,45 17,46.9 20,46.9 20.9,49.6 21.8,46.9 24.9,46.9 22.5,45 	"/>
                                    	<polygon fill="#262826" points="31.5,41.5 30.7,38.8 29.7,41.5 26.8,41.5 29.1,43.4 28.1,46.1 30.6,44.4 33,46.1 32.1,43.4 
                                    		34.5,41.7 	"/>
                                    	<polygon fill="#262826" points="40,32.7 37.6,34.1 35.3,32.4 36.1,35.3 33.6,36.9 36.5,37 37.4,39.8 38.4,37 41.4,37.2 39.1,35.5 	
                                    		"/>
                                    	<polygon fill="#262826" points="12.1,41.5 11.1,38.8 10.3,41.5 7.4,41.7 9.8,43.4 9,46.1 11.3,44.4 13.6,46.1 12.7,43.4 15.1,41.5 
                                    			"/>
                                    	<polygon fill="#262826" points="5.7,35.3 6.5,32.4 4.2,34.1 1.8,32.7 2.8,35.5 0.4,37.2 3.4,37 4.4,39.8 5.3,37 8.2,36.9 	"/>
                                    	<polygon fill="#262826" points="18.8,7.7 21.1,5.9 23.6,7.7 22.7,5 25,3.1 22,3.1 21.1,0.4 20.2,3.1 17.2,3.1 19.7,5 	"/>
                                    	<polygon fill="#262826" points="10.5,8.4 11.4,11.2 12.3,8.5 15.3,8.5 13.1,6.7 13.9,4 11.6,5.6 9.1,3.9 10,6.7 7.6,8.4 	"/>
                                    	<polygon fill="#262826" points="2,17.4 4.5,15.7 6.8,17.6 6.1,14.7 8.4,13.1 5.5,13 4.7,10.2 3.7,12.9 0.7,12.8 3,14.7 	"/>
                                    	<polygon fill="#262826" points="30,8.5 30.9,11.2 31.7,8.4 34.8,8.4 32.3,6.7 33.2,3.9 30.9,5.6 28.4,4 29.4,6.7 27,8.5 	"/>
                                    	<polygon fill="#262826" points="36.4,14.7 35.6,17.6 37.8,15.7 40.3,17.4 39.3,14.7 41.6,12.8 38.6,12.9 37.7,10.2 36.9,13 
                                    		33.8,13.1 	"/>
                                    </g>
                                    </svg>
                                </div>
                            </div>
                            <div class="choose-title">
                                <h5>Best Value</h5>
                            </div>
                            <div class="choose-des">
                               <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p> 
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-12">
                        <div class="single-choose text-center">
                            <div class="choose-icon pos-rltv">
                                <div class="svg">
                                	<svg version="1.1" class="svg-airplane" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                    	 viewBox="0 0 42 50" enable-background="new 0 0 42 50" xml:space="preserve">
                                    <g>
                                    	<path fill="#262826" d="M13.2,30.8c-0.2-0.6-0.2-1-0.2-1.4c-3.2,1.4-5.2,2.8-4.9,3.4l0,0C8.1,32.9,8.2,33,8.3,33
                                    		c0.1,0,0.2,0,0.3,0.1c0.9,0.2,2.9-0.1,5.4-1c-0.2-0.1-0.4-0.5-0.6-0.8C13.3,31.1,13.3,31,13.2,30.8z"/>
                                    	<path fill="#262826" d="M14.5,31.9c0.1-0.1,0.1-0.2,0.1-0.3c0.1-0.2,0.1-0.5,0-0.8c0-0.2-0.1-0.4-0.1-0.5c-0.2-0.5-0.5-0.9-0.7-1
                                    		c0,0-0.1,0-0.2,0l0,0c-0.1,0-0.1,0-0.2,0.1c-0.1,0.2-0.1,0.7,0.2,1.3c0.1,0.2,0.2,0.4,0.2,0.4c0.2,0.4,0.4,0.6,0.6,0.8
                                    		C14.3,31.9,14.4,31.9,14.5,31.9L14.5,31.9z"/>
                                    	<path fill="#262826" d="M40.5,18.1L6.2,31l1.5,1.5c0.4-1.1,3-2.6,5.6-3.6l0,0l0,0h0.1l0.2-0.1v0.1c0.4,0,0.9,0.5,1.2,1.3
                                    		c0.1,0.1,0.1,0.2,0.1,0.4l4.3-1.7l-3.5,6l4.2-1.7l7.3-7.4l7.3-2.8l0.9-0.3c0,0,0,0,0.1-0.1c1.2-0.6,1.4-0.6,3.8-1.7
                                    		c2.9-1.3,2.6-2.3,2.6-2.3C41.8,18.4,41.5,18.2,40.5,18.1z"/>
                                    	<path fill="#262826" d="M39.4,18.1l-6.4-0.6c-1,0-1.8,0.2-2.4,0.5l-5.5,2l-4.3-0.8l-3.1,1.2l2.1,1.8L9.2,26.7l-6.4-2.8L0.1,25
                                    		l3.2,2.3l-1.3,2.5l1.7-0.7L4,28.8l2.5-2.6L6.7,26l0.3,0.3l-2.4,2.6l1.1,1.7h0l33.4-12.2L39.4,18.1z M16.7,25.8l-2.2,0.9l-0.2-1.3
                                    		l2.3-0.9L16.7,25.8z M20.4,24.4l-2.2,0.9L18,23.9l2.3-0.8L20.4,24.4z M24,22.9l-2.2,0.9l-0.1-1.3l2.1-0.8L24,22.9z M27.7,21.5
                                    		l-2.2,0.9l-0.2-1.2l2.2-0.8L27.7,21.5z M32.3,18.3c-0.1-0.4,0.1-0.5,0.4-0.7c0,0,5,0.6,5.1,0.6c-0.1,0-3.2,1.2-3.2,1.2
                                    		C33.6,19.7,32.7,19.2,32.3,18.3z"/>
                                    </g>
                                    </svg>
                                </div>
                            </div>
                            <div class="choose-title">
                                <h5>Fast Delivery</h5>
                            </div>
                            <div class="choose-des">
                               <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p> 
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 hidden-sm col-xs-12">
                        <div class="single-choose text-center">
                            <div class="choose-icon pos-rltv">
                                <div class="svg">
                                	<svg version="1.1" class="svg-tag" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                    	 viewBox="0 0 42 50" enable-background="new 0 0 42 50" xml:space="preserve">
                                    <g>
                                    	<path fill="#262826" d="M40.8,6c-0.5-0.4-1.3-0.8-2.6-0.4c-1.8,0.4-4.4,3.3-6.2,6c-3.9,0.2-11.5,0.3-12,0.8L0.9,30.1
                                    		c-0.8,0.8-0.9,2-0.2,2.7l10.2,11.2c0.7,0.8,1.9,0.8,2.6,0.1l19.2-17.8c0.6-0.4,1.1-6.6,1.4-10.8c0.5-0.3,1.3-0.5,1.8-0.8
                                    		c2.5-1.2,5.9-2.8,6.1-5.2C42.1,8,41.7,6.7,40.8,6z M29.7,26.9L13.5,41.7c-0.7,0.7-1.9,0.7-2.6,0l-8-8.7c-0.8-0.8-0.7-2.1,0-2.7
                                    		l16.2-14.8c0.8-0.8,2-0.8,2.7,0l8.1,8.8C30.5,25,30.4,26.2,29.7,26.9z M31.5,17.4c-0.9,0.8-2.3,0.8-3.2-0.2c-0.8-1-0.7-2.3,0.1-3.2
                                    		c0.7-0.6,1.5-0.7,2.3-0.4c-0.1,0.3-0.4,0.5-0.5,0.8c-0.3,0-0.5,0.2-0.9,0.4c-0.5,0.3-0.5,1.1-0.1,1.6c0.5,0.4,1.1,0.4,1.7,0
                                    		c0.4-0.3,0.4-1.2,0-1.5c0.1-0.3,0.3-0.6,0.4-0.9c0.1,0.1,0.1,0.1,0.2,0.1C32.5,15.1,32.5,16.5,31.5,17.4z M41.2,9.5
                                    		c-0.1,1.9-3.3,3.4-5.6,4.4c-0.4,0.2-1,0.5-1.4,0.8c0.2-1.8,0.2-3.2,0.2-3.2s-0.5,0.2-1.3,0.2c1.7-2.5,3.9-4.9,5.4-5.2
                                    		c0.7-0.3,1.4-0.2,1.9,0.2C41,7.2,41.2,8.3,41.2,9.5z"/>
                                    	<polygon fill="#262826" points="12,29.7 11.1,28.8 7.5,32.3 8.3,33.1 9.6,32 13.2,35.9 14.4,34.8 10.6,30.9 	"/>
                                    	<path fill="#262826" d="M12.3,27.7l3.1,6.2l1.2-1.2l-0.9-1.6l1.5-1.2l1.5,0.8l1.1-1.2l-6-3.4L12.3,27.7z M14.9,28.5l1.3,0.7
                                    		l-1.1,1.1L14.4,29c-0.1-0.5-0.4-0.7-0.6-1.2l0,0C14.1,28.1,14.4,28.3,14.9,28.5z"/>
                                    	<path fill="#262826" d="M19.9,24.4l0.9,1l0.7-0.7l1.1,1.1c-0.1,0-0.3,0.3-0.6,0.5c-0.9,0.8-2.1,0.8-3-0.1C18,25,18.1,23.9,19.1,23
                                    		c0.5-0.5,0.9-0.7,1.4-0.8l-0.7-1.1c-0.3,0.1-1,0.3-1.5,1c-1.6,1.5-1.9,3.4-0.4,5.1c0.7,0.7,1.5,1.1,2.3,1.1c0.8,0,1.6-0.4,2.5-1.2
                                    		c0.7-0.5,1.1-1.4,1.4-1.8l-2.5-2.6L19.9,24.4z"/>
                                    </g>
                                    </svg>
                                </div>
                            </div>
                            <div class="choose-title">
                                <h5>Trending</h5>
                            </div>
                            <div class="choose-des">
                               <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p> 
                            </div>
                        </div>
                    </div>')
            ?>
    	</div>
    </div>
</div>
<!--choose us area start-->

<!--better-area start-->
<div class="better-area pb-70">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-center">
                <div class="heading-title heading-style pos-rltv mb-50 text-center">
                    <h5 class="uppercase"><?php echo $this->MelisTag($this->idPage, 'about_part3_title', 'textarea', 'We Are Better')?></h5> 
                </div>
            </div>
            <div class="col-md-6 col-sm-6">
            <?php 
                echo $this->MelisTag($this->idPage, 'about_part3_text', 'html',
                '<div class="skill-content">
                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </p>
                        <div class="powerfull-skills">
                            <div class="single-prograss">
                                <div class="progess-heading"> Photoshop <span>(79%)</span> </div>
                                <div class="progress">
                                    <div class="progress-bar pr-blue wow fadeInLeft" style="width:79%" data-wow-duration="2s" data-wow-delay="1s"> </div>
                                </div>
                            </div>
                            <div class="single-prograss">
                                <div class="progess-heading"> Illustrator <span>(96%)</span> </div>
                                <div class="progress">
                                    <div class="progress-bar pr-green wow fadeInLeft" style="width:96%" data-wow-duration="2s" data-wow-delay="1s"> </div>
                                </div>
                            </div>
                            <div class="single-prograss">
                                <div class="progess-heading pr-voilate"> HTML <span>(85%)</span> </div>
                                <div class="progress">
                                    <div class="progress-bar pr-violate wow fadeInLeft" style="width:85%" data-wow-duration="2s" data-wow-delay="1s"> </div>
                                </div>
                            </div>
                            <div class="single-prograss">
                                <div class="progess-heading"> Wordpress <span>(92%)</span> </div>
                                <div class="progress">
                                    <div class="progress-bar pr-ornage wow fadeInLeft" style="width:92%" data-wow-duration="2s" data-wow-delay="1s"> </div>
                                </div>
                            </div>
                        </div>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. will be distracted by the readable content of a page when looking at its layout. </p>
                    </div>')
            ?>
            </div>
            <div class="col-md-6 col-sm-6">
            	<div class="skill-img">
                	<?php 
                        echo $this->MelisTag($this->idPage, 'about_part3_image', 'media',
                            '<img src="/MelisDemoCms/images/blog/about02.jpg" alt="">')
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!--better-area end-->

<!--out team area start-->
<div class="our-team-area pb-70">
    <div class="container">
        <div class="row"> 
            <div class="col-xs-12 text-center">
                <div class="heading-title heading-style pos-rltv mb-50 text-center">
                    <h5 class="uppercase"><?php echo $this->MelisTag($this->idPage, 'about_part4_title', 'textarea', 'Our Team')?></h5> 
                </div>
            </div> 
        </div>
        <!-- Out team slider -->
        <?php echo $this->aboutUsSlider?>
        <!-- End of slider -->
    </div>
</div>
<!--out team area end-->