<?php

$siteDemoCmsForm = $this->siteDemoCmsForm;
$formId          = $siteDemoCmsForm->getAttributes()['id'];

echo "<h3>MelisDemoCms Setup</h3>";
echo $this->form()->openTag($siteDemoCmsForm);
echo "<fieldset id='$formId'>";
foreach($siteDemoCmsForm->getElements() as $element => $attributes)  {
    $el =  $siteDemoCmsForm->get((string) $element);
    $label=$el->getLabel();
    $toolTip = $this->translate($el->getOptions()['tooltip']);

    echo '<div class="form-group">';
    echo '<label for="'.$el->getAttributes()['name'].'">'.$this->translate($label);
    echo   "<i class='fa fa-info-circle fa-lg pull-right' data-toggle='tooltip' data-placement='left' title='$toolTip' ></i>";
    echo '</label>';
    echo '<input type="'.$el->getAttributes()['type'].'" name="'.$el->getAttributes()['name'].'" class="'. $el->getAttributes()['class'] .'" placeholder="'. $el->getAttributes()['placeholder'] .'">';
    echo '</div>'.PHP_EOL;


}
echo "</fieldset>";
echo $this->form()->closeTag();
?>