<!doctype html>
<html class="no-js" lang="en">
    <head>
      	<title>Melis Demo CMS Setup</title>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php
            // Favicon
            $this->headLink(array('rel' => 'apple-touch-icon', 'href' => $this->basePath('/MelisDemoCms/images/icons/favicon.ico'), 'PREPEND'));
            // Bootstrap fremwork main css
            $this->headLink()->appendStylesheet('/MelisDemoCms/css/bootstrap.min.css');
            $this->headLink()->appendStylesheet('/MelisDemoCms/css/font-awesome.min.css');
            // Generate Styles
            echo $this->headLink();
        ?>
        <style>
        .jumbotron .alert-info p, .jumbotron .alert-warning p {
            margin-bottom: 3px;
            font-size: 15px;
            font-weight: 200;
        }
        .jumbotron .alert-success p{
           font-size: 19px;
            margin-top: 8px;
        }
        </style>
    </head>
    <body>
        <br>
        <div class="container">
        	<div class="jumbotron">
              	<h1>Melis Demo CMS Setup</h1>
              	<div class="alert alert-info hidden" role="alert">
            		<i class="fa fa-cog fa-spin fa-3x fa-fw pull-left"></i>
					<p><strong>MelisDemoCms setup started.</strong></p>
					<p>Please wait while the setup is running, this may take a few minutes.</p>
            	</div>
            	<div class="alert alert-success hidden" role="alert">
            		<i class="fa fa-check-circle fa-3x pull-left"></i>
					<p><strong>MelisDemoCms setup completed.</strong></p>
            	</div>
            	<div class="alert alert-warning hidden" role="alert">
            		<i class="fa fa-info-circle fa-3x pull-left"></i>
					<p><strong>Opps... Something went wrong.</strong></p>
					<p>An error has occurred, please contact the administrator if the problem persists.</p>
            	</div>
            	<div class="form-group siteProtocolForm">
                    <label for="siteDomain">Protocol</label>
                    <select class="form-control" id="siteProtocol">
                    	<option value="" selected>-select-</option>
                    	<option value="http">http</option>
                    	<option value="https">https</option>
                    </select>
                </div>
              	<div class="form-group siteDomainForm">
                    <label for="siteDomain">Site Domain</label>
                    <input type="text" class="form-control" id="siteDomain" placeholder="www.test.com">
                </div>
              	<p><button class="btn btn-success btn-lg" id="setupStartbtn">Start setup</button></p>
            </div>
        </div>

        <?php
            // jquery latest version
            $this->inlineScript()->appendFile($this->basePath('/MelisDemoCms/js/vendor/jquery-2.2.4.min.js'));
            // Bootstrap framework js
            $this->inlineScript()->appendFile($this->basePath('/MelisDemoCms/js/bootstrap.min.js'));
            // Generate JS
            echo $this->inlineScript();
        ?>
        <script type="text/javascript">
            $("#setupStartbtn").click(function(){

            	var noError = true;
            	var protocol = $("#siteProtocol").val();
              	if(protocol.trim().length){
              		$(".siteProtocolForm").removeClass("has-error");
          		}else{
					$(".siteProtocolForm").addClass("has-error");
					noError = false;
          		}

            	var domain = $("#siteDomain").val();
              	if(domain.trim().length){
              		$(".siteDomainForm").removeClass("has-error");
          		}else{
					$(".siteDomainForm").addClass("has-error");
					noError = false;
          		}

          		if(noError){
          			$(".alert").addClass("hidden");
                    $(".alert-info").removeClass("hidden");
                    $(this).attr('disabled', true);
                 	executeSetup();
          		}
            });

            function executeSetup(step = ''){
                var dataString = new Array;
                dataString.push({
                    name : "step",
                    value : step
                });

                dataString.push({
                    name : "protocol",
                    value : $("#siteProtocol").val()
                });

                dataString.push({
                    name : "domain",
                    value : $("#siteDomain").val()
                });

                $("#siteProtocol").attr("disabled", true);
                $("#siteDomain").attr("disabled", true);

                $.ajax({
        			type        : 'POST',
        	        url         : '/MelisDemoCms/setup/executeSetup',
        	        data        : dataString,
        	        dataType    : 'json',
        	        encode		: true
        		}).success(function(data){
        			$(".alert").addClass("hidden");
    				$("#setupStartbtn").addClass("hidden");
    				$(".alert-success").removeClass("hidden");
        		}).fail(function(){
        			$(".alert").addClass("hidden");
        			$(".alert-warning").removeClass("hidden");
        		});;
            }
        </script>
    </body>
</html>